"""This script replays an InterMimic motion tensor and outputs it to a npz file.

The InterMimic file is a bare ``torch.float32`` tensor of shape ``(T, raw)`` sampled at a
fixed fps, with the layout built by ``_make_obs_layout(num_bodies, num_dof)``::

    root_pos      [0:3]                       world frame, m
    root_rot      [3:7]                       quaternion, xyzw
    root_lin_vel  [7:10]                      world frame, m/s
    root_ang_vel  [10:13]                     world frame, rad/s
    dof_pos       [13 : 13+ND]                rad
    dof_vel       [13+ND : 13+2*ND]           rad/s
    obj_pos       [13+2*ND : 16+2*ND]         world frame, m
    obj_rot       [16+2*ND : 20+2*ND]         quaternion, xyzw
    obj_lin_vel   [20+2*ND : 23+2*ND]         world frame, m/s
    obj_ang_vel   [23+2*ND : 26+2*ND]         world frame, rad/s
    body_*        [26+2*ND : 26+2*ND+13*NB]   ignored, regenerated from the Booster model
    contact       trailing NB                 ignored

The object block is carried straight through to the output npz (as ``object_pos_w``,
``object_quat_w``, ``object_lin_vel_w``, ``object_ang_vel_w``): unlike the robot body block,
there is no differing source/target body set to reconcile, so no re-simulation is needed.

Reference points match Isaac Lab throughout: positions and orientations are link frame,
linear velocities are center of mass, and angular velocity is frame-independent. That is
exactly how ``write_root_state_to_sim`` reads a root state, so the root block transfers
with no conversion beyond the quaternion layout.

Unlike :file:`csv_to_npz.py`, joint and root velocities are taken straight from the file
rather than finite-differenced from the positions, so fast parts of the motion keep their
true derivatives. The body blocks are still discarded and regenerated by driving the
Booster articulation, because the source model exposes a different body set, ordering and
link geometry than the Booster K1 model the policy is trained against.

.. code-block:: bash

    # Usage
    python pt_to_npz.py --headless \
        --input_file ./booster_assets/motions/K1/sub4_smallbox_047_smallbox_intermimic_original.pt \
        --output_name ./booster_assets/motions/K1/sub4_smallbox_047.npz
"""

"""Launch Isaac Sim Simulator first."""

import argparse
import sys
import numpy as np

from isaaclab.app import AppLauncher

# add argparse arguments
parser = argparse.ArgumentParser(description="Replay an InterMimic motion tensor and output to a npz file.")
parser.add_argument("--input_file", type=str, required=True, help="The path to the input InterMimic .pt file.")
parser.add_argument("--input_fps", type=int, default=50, help="The fps of the input motion.")
parser.add_argument(
    "--frame_range",
    nargs=2,
    type=int,
    metavar=("START", "END"),
    help=(
        "frame range: START END (both inclusive). The frame index starts from 1. If not provided, all frames will be"
        " loaded."
    ),
)
parser.add_argument("--output_name", type=str, required=True, help="The name of the motion npz file.")
parser.add_argument("--output_fps", type=int, default=50, help="The fps of the output motion. Must equal --input_fps.")
parser.add_argument("--num_dof", type=int, default=22, help="Number of actuated DOF in the source file (K1: 22).")

# append AppLauncher cli args
AppLauncher.add_app_launcher_args(parser)
# parse the arguments
args_cli = parser.parse_args()

# launch omniverse app
app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

"""Rest everything follows."""

import torch

import isaaclab.sim as sim_utils
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObject, RigidObjectCfg
from isaaclab.scene import InteractiveScene, InteractiveSceneCfg
from isaaclab.sim import SimulationContext
from isaaclab.utils import configclass
from isaaclab.utils.assets import ISAAC_NUCLEUS_DIR

##
# Pre-defined configs
##
from booster_train.assets.robots.booster import BOOSTER_K1_CFG as ROBOT_CFG
from booster_train.assets.objects.boxes import SMALLBOX_0539923_CFG as OBJECT_CFG

# The source DOF order, one row per actuated joint, in the order the columns appear in the
# .pt file. Each row lists the aliases this joint is known by, because the InterMimic
# retarget model, the Booster URDF and booster_assets.motions all spell it differently.
# The order below is the joint order of the InterMimic K1 MJCF and is identical to
# booster_assets.motions.K1_JOINT_NAMES.
K1_DOF_ALIASES = [
    ("AAHead_yaw", "aahead_yaw_joint"),
    ("Head_pitch", "aahead_pitch_joint"),
    ("ALeft_Shoulder_Pitch", "aaleft_shoulder_pitch_joint", "left_shoulder_pitch_joint"),
    ("Left_Shoulder_Roll", "left_shoulder_roll_joint"),
    ("Left_Elbow_Pitch", "left_elbow_pitch_joint"),
    ("Left_Elbow_Yaw", "left_elbow_yaw_joint"),
    ("ARight_Shoulder_Pitch", "aaright_shoulder_pitch_joint", "right_shoulder_pitch_joint"),
    ("Right_Shoulder_Roll", "right_shoulder_roll_joint"),
    ("Right_Elbow_Pitch", "right_elbow_pitch_joint"),
    ("Right_Elbow_Yaw", "right_elbow_yaw_joint"),
    ("Left_Hip_Pitch", "left_hip_pitch_joint"),
    ("Left_Hip_Roll", "left_hip_roll_joint"),
    ("Left_Hip_Yaw", "left_hip_yaw_joint"),
    ("Left_Knee_Pitch", "left_knee_pitch_joint"),
    ("Left_Ankle_Pitch", "left_ankle_pitch_joint"),
    ("Left_Ankle_Roll", "left_ankle_roll_joint"),
    ("Right_Hip_Pitch", "right_hip_pitch_joint"),
    ("Right_Hip_Roll", "right_hip_roll_joint"),
    ("Right_Hip_Yaw", "right_hip_yaw_joint"),
    ("Right_Knee_Pitch", "right_knee_pitch_joint"),
    ("Right_Ankle_Pitch", "right_ankle_pitch_joint"),
    ("Right_Ankle_Roll", "right_ankle_roll_joint"),
]

# Bodies the shipped K1 tracking tasks ask for. Only used to warn when the spawned model
# cannot supply them, which means the baked npz will not load in those tasks.
TASK_BODY_NAMES = [
    "Trunk",
    "Head_2",
    "Left_Hip_Roll",
    "Left_Shank",
    "left_foot_link",
    "Right_Hip_Roll",
    "Right_Shank",
    "right_foot_link",
    "Left_Arm_2",
    "Left_Arm_3",
    "left_hand_link",
    "Right_Arm_2",
    "Right_Arm_3",
    "right_hand_link",
]


@configclass
class ReplayMotionsSceneCfg(InteractiveSceneCfg):
    """Configuration for a replay motions scene."""

    # ground plane
    ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())

    # lights
    sky_light = AssetBaseCfg(
        prim_path="/World/skyLight",
        spawn=sim_utils.DomeLightCfg(
            intensity=750.0,
            texture_file=f"{ISAAC_NUCLEUS_DIR}/Materials/Textures/Skies/PolyHaven/kloofendal_43d_clear_puresky_4k.hdr",
        ),
    )

    # articulation
    robot: ArticulationCfg = ROBOT_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")

    # tracked object
    object: RigidObjectCfg = OBJECT_CFG.replace(prim_path="{ENV_REGEX_NS}/Object")


class InterMimicMotionLoader:
    def __init__(
        self,
        motion_file: str,
        input_fps: int,
        output_fps: int,
        num_dof: int,
        device: torch.device,
        frame_range: tuple[int, int] | None,
    ):
        if input_fps != output_fps:
            raise ValueError(
                f"--input_fps ({input_fps}) must equal --output_fps ({output_fps}). Resampling would force the"
                " velocities to be re-derived from interpolated positions, which is the artifact this script exists"
                " to avoid. Resample the source motion instead."
            )
        self.motion_file = motion_file
        self.input_fps = input_fps
        self.output_fps = output_fps
        self.output_dt = 1.0 / self.output_fps
        self.num_dof = num_dof
        self.current_idx = 0
        self.device = device
        self.frame_range = frame_range
        self._load_motion()

    def _load_motion(self):
        """Loads the motion from the InterMimic .pt file."""
        motion = torch.load(self.motion_file, map_location="cpu", weights_only=False)
        if not torch.is_tensor(motion):
            raise TypeError(f"Expected a bare torch.Tensor in {self.motion_file}, got {type(motion)}.")
        if motion.ndim != 2:
            raise ValueError(f"Expected a (T, raw) tensor, got shape {tuple(motion.shape)}.")

        # raw = 26 + 2 * ND + 14 * NB, so NB follows from the tensor width.
        nd = self.num_dof
        residual = motion.shape[1] - 26 - 2 * nd
        if residual <= 0 or residual % 14 != 0:
            raise ValueError(
                f"Tensor width {motion.shape[1]} is not consistent with num_dof={nd}: expected"
                f" 26 + 2*{nd} + 14*NB for an integer NB."
            )
        self.num_bodies = residual // 14

        if self.frame_range is not None:
            motion = motion[self.frame_range[0] - 1 : self.frame_range[1]]
        motion = motion.to(torch.float32).to(self.device)
        self.raw = motion

        self.motion_base_poss = motion[:, 0:3]
        self.motion_base_rots = motion[:, 3:7][:, [3, 0, 1, 2]]  # convert to wxyz
        self.motion_base_lin_vels = motion[:, 7:10]
        self.motion_base_ang_vels = motion[:, 10:13]
        self.motion_dof_poss = motion[:, 13 : 13 + nd]
        self.motion_dof_vels = motion[:, 13 + nd : 13 + 2 * nd]

        obj_start = 13 + 2 * nd
        self.motion_object_poss = motion[:, obj_start : obj_start + 3]
        self.motion_object_rots = motion[:, obj_start + 3 : obj_start + 7][:, [3, 0, 1, 2]]  # convert to wxyz
        self.motion_object_lin_vels = motion[:, obj_start + 7 : obj_start + 10]
        self.motion_object_ang_vels = motion[:, obj_start + 10 : obj_start + 13]

        # Kept only for the post-bake diagnostics; the final reference regenerates these.
        body_start = 26 + 2 * nd
        nb = self.num_bodies
        self.source_body_poss = motion[:, body_start : body_start + nb * 3].view(-1, nb, 3)
        self.source_body_lin_vels = motion[:, body_start + nb * 7 : body_start + nb * 10].view(-1, nb, 3)

        quat_norm = self.motion_base_rots.norm(dim=-1)
        if not torch.allclose(quat_norm, torch.ones_like(quat_norm), atol=1e-3):
            raise ValueError(f"Root quaternions are not unit norm (min {quat_norm.min()}, max {quat_norm.max()}).")

        obj_quat_norm = self.motion_object_rots.norm(dim=-1)
        if not torch.allclose(obj_quat_norm, torch.ones_like(obj_quat_norm), atol=1e-3):
            raise ValueError(
                f"Object quaternions are not unit norm (min {obj_quat_norm.min()}, max {obj_quat_norm.max()})."
            )

        self.output_frames = motion.shape[0]
        self.duration = (self.output_frames - 1) * self.output_dt
        print(
            f"Motion loaded ({self.motion_file}), duration: {self.duration} sec, frames: {self.output_frames},"
            f" bodies: {self.num_bodies}, dof: {nd}"
        )

    def get_next_state(self):
        """Gets the next state of the motion."""
        state = (
            self.motion_base_poss[self.current_idx : self.current_idx + 1],
            self.motion_base_rots[self.current_idx : self.current_idx + 1],
            self.motion_base_lin_vels[self.current_idx : self.current_idx + 1],
            self.motion_base_ang_vels[self.current_idx : self.current_idx + 1],
            self.motion_dof_poss[self.current_idx : self.current_idx + 1],
            self.motion_dof_vels[self.current_idx : self.current_idx + 1],
            self.motion_object_poss[self.current_idx : self.current_idx + 1],
            self.motion_object_rots[self.current_idx : self.current_idx + 1],
            self.motion_object_lin_vels[self.current_idx : self.current_idx + 1],
            self.motion_object_ang_vels[self.current_idx : self.current_idx + 1],
        )
        self.current_idx += 1
        reset_flag = False
        if self.current_idx >= self.output_frames:
            self.current_idx = 0
            reset_flag = True
        return state, reset_flag


def resolve_joint_indexes(robot_joint_names: list[str], aliases: list[tuple[str, ...]]) -> list[int]:
    """Maps each source DOF column onto an index into the spawned robot's joint order."""
    indexes = []
    unresolved = []
    for row in aliases:
        for name in row:
            if name in robot_joint_names:
                indexes.append(robot_joint_names.index(name))
                break
        else:
            unresolved.append(row)
    if unresolved:
        raise RuntimeError(
            "Could not map every source DOF onto the spawned robot.\n"
            f"  unresolved: {unresolved}\n"
            f"  robot.joint_names: {robot_joint_names}\n"
            "The installed booster_assets K1 model does not match the one this motion was retargeted against."
        )
    if len(set(indexes)) != len(indexes):
        raise RuntimeError(f"Source DOFs mapped onto duplicate robot joints: {indexes}")
    return indexes


def run_simulator(sim: sim_utils.SimulationContext, scene: InteractiveScene):
    """Runs the simulation loop."""
    # Load motion
    motion = InterMimicMotionLoader(
        motion_file=args_cli.input_file,
        input_fps=args_cli.input_fps,
        output_fps=args_cli.output_fps,
        num_dof=args_cli.num_dof,
        device=sim.device,
        frame_range=args_cli.frame_range,
    )

    # Extract scene entities
    robot = scene["robot"]
    obj: RigidObject = scene["object"]
    robot_joint_indexes = resolve_joint_indexes(list(robot.joint_names), K1_DOF_ALIASES)
    if len(robot.joint_names) != len(robot_joint_indexes):
        print(
            f"[WARN]: the robot has {len(robot.joint_names)} joints but the motion only drives"
            f" {len(robot_joint_indexes)}. The rest stay at their default pose."
        )
    missing_bodies = [name for name in TASK_BODY_NAMES if name not in robot.body_names]
    if missing_bodies:
        print(
            f"[WARN]: the spawned model is missing bodies the shipped K1 tasks track: {missing_bodies}.\n"
            f"[WARN]: robot.body_names = {list(robot.body_names)}\n"
            "[WARN]: the npz will still be written, but MotionLoader will raise on these names at train time."
        )

    # ------- data logger -------------------------------------------------------
    log = {
        "fps": [args_cli.output_fps],
        "joint_pos": [],
        "joint_vel": [],
        "body_pos_w": [],
        "body_quat_w": [],
        "body_lin_vel_w": [],
        "body_ang_vel_w": [],
        "object_pos_w": [],
        "object_quat_w": [],
        "object_lin_vel_w": [],
        "object_ang_vel_w": [],
        "joint_names": np.array(robot.joint_names),
        "body_names": np.array(robot.body_names),
    }
    file_saved = False
    # --------------------------------------------------------------------------

    # Simulation loop
    while simulation_app.is_running():
        (
            (
                motion_base_pos,
                motion_base_rot,
                motion_base_lin_vel,
                motion_base_ang_vel,
                motion_dof_pos,
                motion_dof_vel,
                motion_object_pos,
                motion_object_rot,
                motion_object_lin_vel,
                motion_object_ang_vel,
            ),
            reset_flag,
        ) = motion.get_next_state()

        # set root state
        root_states = robot.data.default_root_state.clone()
        root_states[:, :3] = motion_base_pos
        root_states[:, :2] += scene.env_origins[:, :2]
        root_states[:, 3:7] = motion_base_rot
        root_states[:, 7:10] = motion_base_lin_vel
        root_states[:, 10:] = motion_base_ang_vel
        # write_root_state_to_sim reads [:7] as the link-frame pose and [7:] as the
        # center-of-mass velocity, which is the source file's convention exactly.
        robot.write_root_state_to_sim(root_states)

        # set joint state
        joint_pos = robot.data.default_joint_pos.clone()
        joint_vel = robot.data.default_joint_vel.clone()
        joint_pos[:, robot_joint_indexes] = motion_dof_pos
        joint_vel[:, robot_joint_indexes] = motion_dof_vel
        robot.write_joint_state_to_sim(joint_pos, joint_vel)

        # set object state (kinematic replay, same convention as the robot root above)
        object_states = obj.data.default_root_state.clone()
        object_states[:, :3] = motion_object_pos
        object_states[:, :2] += scene.env_origins[:, :2]
        object_states[:, 3:7] = motion_object_rot
        object_states[:, 7:10] = motion_object_lin_vel
        object_states[:, 10:] = motion_object_ang_vel
        obj.write_root_state_to_sim(object_states)

        sim.render()  # We don't want physic (sim.step())
        scene.update(sim.get_physics_dt())

        pos_lookat = root_states[0, :3].cpu().numpy()
        sim.set_camera_view(pos_lookat + np.array([2.0, 2.0, 0.5]), pos_lookat)

        if not file_saved:
            log["joint_pos"].append(robot.data.joint_pos[0, :].cpu().numpy().copy())
            log["joint_vel"].append(robot.data.joint_vel[0, :].cpu().numpy().copy())
            log["body_pos_w"].append(robot.data.body_pos_w[0, :].cpu().numpy().copy())
            log["body_quat_w"].append(robot.data.body_quat_w[0, :].cpu().numpy().copy())
            log["body_lin_vel_w"].append(robot.data.body_lin_vel_w[0, :].cpu().numpy().copy())
            log["body_ang_vel_w"].append(robot.data.body_ang_vel_w[0, :].cpu().numpy().copy())
            log["object_pos_w"].append(motion_object_pos[0, :].cpu().numpy().copy())
            log["object_quat_w"].append(motion_object_rot[0, :].cpu().numpy().copy())
            log["object_lin_vel_w"].append(motion_object_lin_vel[0, :].cpu().numpy().copy())
            log["object_ang_vel_w"].append(motion_object_ang_vel[0, :].cpu().numpy().copy())

        if reset_flag and not file_saved:
            file_saved = True
            for k in (
                "joint_pos",
                "joint_vel",
                "body_pos_w",
                "body_quat_w",
                "body_lin_vel_w",
                "body_ang_vel_w",
                "object_pos_w",
                "object_quat_w",
                "object_lin_vel_w",
                "object_ang_vel_w",
            ):
                log[k] = np.stack(log[k], axis=0)

            report_bake_quality(log, motion, robot)
            np.savez(f"{args_cli.output_name}", **log)
            print(f"[INFO]: Motion saved to {args_cli.output_name}")
            sys.exit(0)


def report_bake_quality(log: dict, motion: InterMimicMotionLoader, robot):
    """Cross-checks the regenerated bodies against the source file."""
    root_body_index = 0
    src_root_pos = motion.motion_base_poss.cpu().numpy()
    baked_root_pos = log["body_pos_w"][:, root_body_index]
    pos_err = np.abs(baked_root_pos - src_root_pos).max()

    src_root_vel = motion.source_body_lin_vels[:, root_body_index].cpu().numpy()
    baked_root_vel = log["body_lin_vel_w"][:, root_body_index]
    vel_err = np.abs(baked_root_vel - src_root_vel).max()

    min_z = log["body_pos_w"][..., 2].min()
    min_z_body = robot.body_names[int(np.argmin(log["body_pos_w"][..., 2].min(axis=0)))]

    obj_min_z = log["object_pos_w"][..., 2].min()
    obj_max_z = log["object_pos_w"][..., 2].max()

    print("[CHECK]: ---- bake quality ----")
    print(f"[CHECK]: frames baked                    : {log['body_pos_w'].shape[0]}")
    print(f"[CHECK]: root pos round-trip (max abs)   : {pos_err:.6f} m   (expect ~0)")
    print(f"[CHECK]: root lin vel round-trip (max abs): {vel_err:.6f} m/s (expect ~0)")
    print(f"[CHECK]: lowest body over the motion     : {min_z:.4f} m on '{min_z_body}'")
    print(f"[CHECK]: object height range              : [{obj_min_z:.4f}, {obj_max_z:.4f}] m")
    if pos_err > 1e-3:
        print("[CHECK]: WARNING root position did not round-trip; the source root frame likely differs from Trunk.")
    if vel_err > 1e-2:
        print("[CHECK]: WARNING root velocity did not round-trip; check the source velocity reference point.")
    if min_z < -0.02:
        print("[CHECK]: WARNING bodies penetrate the ground plane; the motion may need a z offset.")
    if obj_min_z < -0.02:
        print("[CHECK]: WARNING object penetrates the ground plane; check the object frame convention.")


def main():
    """Main function."""
    # Load kit helper
    sim_cfg = sim_utils.SimulationCfg(device=args_cli.device)
    sim_cfg.dt = 1.0 / args_cli.output_fps
    sim = SimulationContext(sim_cfg)
    # Design scene
    scene_cfg = ReplayMotionsSceneCfg(num_envs=1, env_spacing=2.0)
    scene = InteractiveScene(scene_cfg)
    # Play the simulator
    sim.reset()
    # Now we are ready!
    print("[INFO]: Setup complete...")
    # Run the simulator
    run_simulator(sim, scene)


if __name__ == "__main__":
    # run the main function
    main()
    # close sim app
    simulation_app.close()
