"""This script replays an InterMimic motion tensor and outputs it to a npz file.

The InterMimic file is a bare ``torch.float32`` tensor of shape ``(T, raw)`` sampled at a
fixed fps, with the layout built by ``_make_obs_layout(num_bodies, num_dof)``::

    root_pos      [0:3]                       world frame, m
    root_rot      [3:7]                       quaternion, xyzw
    root_lin_vel  [7:10]                      world frame, m/s
    root_ang_vel  [10:13]                     world frame, rad/s
    dof_pos       [13 : 13+ND]                rad
    dof_vel       [13+ND : 13+2*ND]           rad/s
    obj_pos       [13+2*ND : 16+2*ND]         world frame, m
    obj_rot       [16+2*ND : 20+2*ND]         quaternion, xyzw
    obj_lin_vel   [20+2*ND : 23+2*ND]         world frame, m/s
    obj_ang_vel   [23+2*ND : 26+2*ND]         world frame, rad/s
    body_*        [26+2*ND : 26+2*ND+13*NB]   ignored, regenerated from the Booster model
    contact       trailing NB                 per-body 0/1; CONTACT_CHANNELS carried through, and
                                              STANCE_CHANNELS as ``stance`` when the file has them

The object block is carried straight through to the output npz (as ``object_pos_w``,
``object_quat_w``, ``object_lin_vel_w``, ``object_ang_vel_w``): unlike the robot body block,
there is no differing source/target body set to reconcile, so no re-simulation is needed.

Reference points match Isaac Lab throughout: positions and orientations are link frame,
linear velocities are center of mass, and angular velocity is frame-independent. That is
exactly how ``write_root_state_to_sim`` reads a root state, so the root block transfers
with no conversion beyond the quaternion layout.

Unlike :file:`csv_to_npz.py`, joint and root velocities are taken straight from the file
rather than finite-differenced from the positions, so fast parts of the motion keep their
true derivatives. The body blocks are still discarded and regenerated by driving the
Booster articulation, because the source model exposes a different body set, ordering and
link geometry than the Booster K1 model the policy is trained against.

.. code-block:: bash

    # Bake only
    python pt_to_npz.py --headless \
        --input_file ./booster_assets/motions/K1/sub4_smallbox_047_smallbox_intermimic_original.pt \
        --output_name ./booster_assets/motions/K1/sub4_smallbox_047.npz

    # Bake + offline/headless MP4 render
    python pt_to_npz.py --headless \
        --input_file ./booster_assets/motions/K1/sub4_smallbox_047_smallbox_intermimic_original.pt \
        --output_name ./booster_assets/motions/K1/sub4_smallbox_047.npz \
        --video ./sub4_smallbox_047.mp4
"""

"""Launch Isaac Sim Simulator first."""

import argparse
import math
import os
import sys
from pathlib import Path
import numpy as np

from isaaclab.app import AppLauncher

# add argparse arguments
parser = argparse.ArgumentParser(description="Replay an InterMimic motion tensor and output to a npz file.")
parser.add_argument("--input_file", type=str, required=True, help="The path to the input InterMimic .pt file.")
parser.add_argument("--input_fps", type=int, default=50, help="The fps of the input motion.")
parser.add_argument(
    "--frame_range",
    nargs=2,
    type=int,
    metavar=("START", "END"),
    help=(
        "frame range: START END (both inclusive). The frame index starts from 1. If not provided, all frames will be"
        " loaded."
    ),
)
parser.add_argument("--output_name", type=str, required=True, help="The name of the motion npz file.")
parser.add_argument("--output_fps", type=int, default=50, help="The fps of the output motion. Must equal --input_fps.")
parser.add_argument("--num_dof", type=int, default=22, help="Number of actuated DOF in the source file (K1: 22).")
parser.add_argument(
    "--object",
    type=str,
    default="smallbox_0539923",
    help=(
        "Which captured object the motion interacts with; must match the source capture. Any directory"
        " booster_assets/motions/K1/<name>/<name>.urdf. Recorded in the npz as object_name, which is how the HOI"
        " task picks the object to simulate."
    ),
)
parser.add_argument("--video", type=str, default=None, help="Optional output MP4 path for offline rendering.")
parser.add_argument("--video_width", type=int, default=1280, help="Rendered video width.")
parser.add_argument("--video_height", type=int, default=720, help="Rendered video height.")
parser.add_argument(
    "--camera_offset",
    type=float,
    nargs=3,
    default=(1.8, 1.8, 0.6),
    metavar=("X", "Y", "Z"),
    help="Camera position offset in world axes relative to the look-at point.",
)
parser.add_argument(
    "--camera_view",
    choices=["world", "front"],
    default="world",
    help=(
        "'world': --camera_offset is in world axes. 'front': --camera_offset is in the robot's heading frame at"
        " frame 0 (x forward, y left), and defaults to (2.2, 0, 0.6), i.e. looking at the robot's face."
    ),
)
parser.add_argument(
    "--camera_focal",
    type=float,
    default=18.0,
    help=(
        "Focal length in mm against a 20.955 mm aperture. 24 mm gives a 28 deg vertical field of view, which"
        " crops a 1.2 m robot at this distance; 18 mm gives 36 deg."
    ),
)
parser.add_argument(
    "--camera_lookat_offset",
    type=float,
    nargs=3,
    default=(0.0, 0.0, -0.05),
    metavar=("X", "Y", "Z"),
    help=(
        "Camera look-at offset in world axes. X/Y track the robot root; Z is measured from the standing root"
        " height of the first frame, so the frame does not dive when the robot squats."
    ),
)
parser.add_argument(
    "--object_physics",
    action="store_true",
    help=(
        "Simulate the object instead of replaying it: it is placed at its frame-0 pose (on a table slab if it"
        " starts off the ground) and then only reacts to contact with the kinematically replayed robot. The npz"
        " then records the simulated object, so write it somewhere other than the training motions."
    ),
)
parser.add_argument(
    "--stand_s",
    type=float,
    default=0.0,
    help=(
        "Append a transition of this many seconds from the clip's last pose to the robot's default standing pose"
        " (see --stand_pose; trunk upright, same heading). Joints follow a cubic Hermite curve"
        " that starts at the clip's final joint velocity and ends at rest; the root is placed every frame so the"
        " lower foot stays on the ground and the feet midpoint stays put. Hold the result with append_hold_npz.py."
    ),
)
parser.add_argument(
    "--stand_pose",
    choices=["prepare", "default"],
    default="prepare",
    help=(
        "Standing pose that --stand_s ends in. 'prepare': booster_deploy's K1 prepare_state pose (knees 0.105,"
        " ankles -0.10, arms down) -- the pose the real robot starts from. 'default': BOOSTER_K1_CFG default joint"
        " angles (straight legs)."
    ),
)
parser.add_argument(
    "--end_mode",
    choices=["stand", "settle"],
    default="stand",
    help=(
        "What the --stand_s transition ends in. 'stand': let go of the object and go to --stand_pose. 'settle': keep"
        " holding it -- arms and head frozen at the clip's last pose, the object carried rigidly with the trunk, hand"
        " contact kept on -- while the legs settle into a stable stance: the foot in stance at the clip end stays"
        " pinned, the trunk turns to face along it and leans --settle_lean_deg forward, both hips straighten in"
        " yaw/roll, knees bend to --settle_knee, and the ankles are solved so both soles end flat on the floor."
    ),
)
parser.add_argument("--settle_knee", type=float, default=0.35, help="Knee bend at the end of --end_mode settle, rad.")
parser.add_argument(
    "--settle_stance_leg",
    choices=["keep", "straighten"],
    default="keep",
    help=(
        "--end_mode settle: what the stance (pinned) leg does in yaw/roll. 'keep': its hip yaw and roll stay at the"
        " clip's last values, so the loaded foot never rotates on the floor (only its pitch/roll flatten). 'straighten':"
        " hip yaw/roll go to 0 like the swing leg, which pivots the loaded foot in place when the trunk heading is kept."
    ),
)
parser.add_argument(
    "--settle_heading",
    choices=["trunk", "foot"],
    default="trunk",
    help=(
        "Final trunk heading for --end_mode settle. 'trunk': keep the clip's last trunk heading -- the stance foot"
        " pivots in place to line up with it. 'foot': turn the trunk to face along the stance foot instead."
    ),
)
parser.add_argument(
    "--settle_lean_deg", type=float, default=8.0, help="Forward trunk lean at the end of --end_mode settle, degrees."
)
parser.add_argument(
    "--start_s",
    type=float,
    default=0.0,
    help=(
        "Prepend a transition of this many seconds from the robot's standing pose (see --start_pose) into the"
        " clip's first pose, so the motion begins where the real robot begins. Joints follow a cubic Hermite"
        " curve that starts at rest and arrives with the clip's initial joint velocity; the root is placed every"
        " frame so the feet stay where the clip's first frame puts them."
    ),
)
parser.add_argument(
    "--start_pose",
    choices=["prepare", "default"],
    default="prepare",
    help="Standing pose that --start_s begins from; same choices as --stand_pose.",
)
parser.add_argument("--object_mass", type=float, default=0.5, help="Object mass with --object_physics, kg.")
parser.add_argument(
    "--robot_drive",
    choices=["teleport", "pd"],
    default="teleport",
    help=(
        "With --object_physics: 'teleport' writes the joint angles every substep (the hands are moved into the"
        " object, not swept, so PhysX only depenetrates it slowly); 'pd' pins the root to the reference but drives"
        " the joints through the K1 actuators toward the reference, so the arms are real colliding bodies."
    ),
)
parser.add_argument(
    "--support_size", type=float, nargs=3, default=(0.6, 0.6, 0.04), metavar=("X", "Y", "Z"),
    help="Table top size with --object_physics, m. Its top face sits at the object's frame-0 bottom.",
)
parser.add_argument(
    "--support_collides_robot", action="store_true",
    help="Let the robot collide with the table (default: filtered out, so a wide table cannot catch the legs).",
)
parser.add_argument(
    "--show_contact_points",
    action="store_true",
    help=(
        "Draw the two palm keypoints into the video (grey when the reference reports no contact, green when it"
        " does) and report how far they sit from the object surface over the labelled contact frames. This is how"
        " --palm_offset is verified: the K1's *_hand_link origin is at the forearm end, not the palm."
    ),
)
parser.add_argument(
    "--palm_offset",
    type=float,
    nargs="+",
    default=[0.20],
    metavar="V",
    help=(
        "Palm keypoint offset in the hand link's frame, m -- the K1's *_hand_link origin sits at the forearm"
        " end, not the palm. One value is the y-only convention (left +y, right -y); three values give the left"
        " hand's full offset and the right hand mirrors it in y."
    ),
)
parser.add_argument("--substeps", type=int, default=4, help="Physics substeps per frame with --object_physics.")

# append AppLauncher cli args
AppLauncher.add_app_launcher_args(parser)
# parse the arguments
args_cli = parser.parse_args()

# Camera sensors require rendering extensions even when running headless.
# Turn them on automatically only when MP4 output was requested.
if args_cli.video is not None:
    args_cli.enable_cameras = True

# launch omniverse app
app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

"""Rest everything follows."""

import torch

import isaaclab.sim as sim_utils
from isaaclab.utils.math import quat_apply, quat_conjugate, quat_mul
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObject, RigidObjectCfg
from isaaclab.scene import InteractiveScene, InteractiveSceneCfg
from isaaclab.sensors import Camera, CameraCfg
from isaaclab.sim import SimulationContext
from isaaclab.utils import configclass
from isaaclab.utils.assets import ISAAC_NUCLEUS_DIR

##
# Pre-defined configs
##
from booster_train.assets.robots.booster import BOOSTER_K1_CFG as ROBOT_CFG
from booster_train.assets.objects.boxes import OBJECT_CFGS, OBJECT_DIR, OBJECT_NAMES

# The object is only replayed kinematically here, but it has to be the right mesh: the npz carries the object
# pose straight through, and the rendered video is what tells you the capture and the asset agree.
if args_cli.object not in OBJECT_CFGS:
    parser.error(f"--object {args_cli.object!r} has no asset; choose one of {OBJECT_NAMES}")
OBJECT_CFG = OBJECT_CFGS[args_cli.object]
OBJECT_MESH = f"{OBJECT_DIR}/{args_cli.object}/{args_cli.object}.obj"
SUPPORT_SIZE = tuple(args_cli.support_size)
SUPPORT_MIN_HEIGHT = 0.05

# The source DOF order, one row per actuated joint, in the order the columns appear in the
# .pt file. Each row lists the aliases this joint is known by, because the InterMimic
# retarget model, the Booster URDF and booster_assets.motions all spell it differently.
# The order below is the joint order of the InterMimic K1 MJCF and is identical to
# booster_assets.motions.K1_JOINT_NAMES.
K1_DOF_ALIASES = [
    ("AAHead_yaw", "aahead_yaw_joint"),
    ("Head_pitch", "aahead_pitch_joint"),
    ("ALeft_Shoulder_Pitch", "aaleft_shoulder_pitch_joint", "left_shoulder_pitch_joint"),
    ("Left_Shoulder_Roll", "left_shoulder_roll_joint"),
    ("Left_Elbow_Pitch", "left_elbow_pitch_joint"),
    ("Left_Elbow_Yaw", "left_elbow_yaw_joint"),
    ("ARight_Shoulder_Pitch", "aaright_shoulder_pitch_joint", "right_shoulder_pitch_joint"),
    ("Right_Shoulder_Roll", "right_shoulder_roll_joint"),
    ("Right_Elbow_Pitch", "right_elbow_pitch_joint"),
    ("Right_Elbow_Yaw", "right_elbow_yaw_joint"),
    ("Left_Hip_Pitch", "left_hip_pitch_joint"),
    ("Left_Hip_Roll", "left_hip_roll_joint"),
    ("Left_Hip_Yaw", "left_hip_yaw_joint"),
    ("Left_Knee_Pitch", "left_knee_pitch_joint"),
    ("Left_Ankle_Pitch", "left_ankle_pitch_joint"),
    ("Left_Ankle_Roll", "left_ankle_roll_joint"),
    ("Right_Hip_Pitch", "right_hip_pitch_joint"),
    ("Right_Hip_Roll", "right_hip_roll_joint"),
    ("Right_Hip_Yaw", "right_hip_yaw_joint"),
    ("Right_Knee_Pitch", "right_knee_pitch_joint"),
    ("Right_Ankle_Pitch", "right_ankle_pitch_joint"),
    ("Right_Ankle_Roll", "right_ankle_roll_joint"),
]

# booster_deploy K1_CFG.prepare_state.joint_pos: the pose the real robot is put in before the policy starts. Listed in
# the source DOF order above (head, left arm, right arm, left leg, right leg), which is also booster_deploy's order.
K1_PREPARE_POSE = [
    0.0, 0.0,
    0.0, -1.3, 0.0, 0.0,
    0.0, 1.3, 0.0, 0.0,
    0.0, 0.0, 0.0, 0.105, -0.10, 0.0,
    0.0, 0.0, 0.0, 0.105, -0.10, 0.0,
]  # fmt: skip

# Bodies the shipped K1 tracking tasks ask for. Only used to warn when the spawned model
# cannot supply them, which means the baked npz will not load in those tasks.
TASK_BODY_NAMES = [
    "Trunk",
    "Head_2",
    "Left_Hip_Roll",
    "Left_Shank",
    "left_foot_link",
    "Right_Hip_Roll",
    "Right_Shank",
    "right_foot_link",
    "Left_Arm_2",
    "Left_Arm_3",
    "left_hand_link",
    "Right_Arm_2",
    "Right_Arm_3",
    "right_hand_link",
]

# Palm keypoints for --show_contact_points. The K1's *_hand_link origin sits at the forearm end, roughly
# --palm_offset metres from the palm along the link's local y, so a contact point taken from the link origin
# alone is off by more than the object is wide. Sign is +y on the left hand, -y on the right.
PALM_BODY_NAMES = ("left_hand_link", "right_hand_link")
PALM_SIGNS = (1.0, -1.0)

# Contact channels carried into the npz, as (source contact index, K1 body name).
CONTACT_CHANNELS = [(6, "left_hand_link"), (11, "right_hand_link")]
CONTACT_SOURCE_INDEXES = [index for index, _ in CONTACT_CHANNELS]
CONTACT_NAMES = [name for _, name in CONTACT_CHANNELS]

# Per-foot reference stance (floor support, 0/1), carried into the npz as ``stance`` -- kept apart from ``contact``,
# which is the hand-object gate and has exactly one channel per hand. Newer exports overwrite the contact bits of
# both each foot link and its sphere_5 toe link with that foot's stance, so the two columns are identical; older
# exports hold unrelated sim contact bits there. That equality is how the format is recognised, and a file without
# it gets no ``stance`` key rather than a mislabelled one. As (foot link index, its toe-sphere index, K1 body name).
STANCE_CHANNELS = [(18, 19, "left_foot_link"), (25, 26, "right_foot_link")]
STANCE_NAMES = [name for _, _, name in STANCE_CHANNELS]


@configclass
class ReplayMotionsSceneCfg(InteractiveSceneCfg):
    """Configuration for a replay motions scene."""

    # ground plane
    ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())

    # lights
    sky_light = AssetBaseCfg(
        prim_path="/World/skyLight",
        spawn=sim_utils.DomeLightCfg(
            intensity=750.0,
            texture_file=f"{ISAAC_NUCLEUS_DIR}/Materials/Textures/Skies/PolyHaven/kloofendal_43d_clear_puresky_4k.hdr",
        ),
    )

    # articulation
    robot: ArticulationCfg = ROBOT_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")

    # tracked object
    object: RigidObjectCfg = OBJECT_CFG.replace(prim_path="{ENV_REGEX_NS}/Object")

    # Table slab under an object that starts off the ground; only spawned with --object_physics.
    support: RigidObjectCfg | None = None

    # Filled in from main() only when --video is requested, so normal NPZ baking
    # does not pay the camera/rendering cost.
    camera: CameraCfg | None = None


class InterMimicMotionLoader:
    def __init__(
        self,
        motion_file: str,
        input_fps: int,
        output_fps: int,
        num_dof: int,
        device: torch.device,
        frame_range: tuple[int, int] | None,
    ):
        if input_fps != output_fps:
            raise ValueError(
                f"--input_fps ({input_fps}) must equal --output_fps ({output_fps}). Resampling would force the"
                " velocities to be re-derived from interpolated positions, which is the artifact this script exists"
                " to avoid. Resample the source motion instead."
            )
        self.motion_file = motion_file
        self.input_fps = input_fps
        self.output_fps = output_fps
        self.output_dt = 1.0 / self.output_fps
        self.num_dof = num_dof
        self.current_idx = 0
        self.device = device
        self.frame_range = frame_range
        self._load_motion()

    def _load_motion(self):
        """Loads the motion from the InterMimic .pt file."""
        motion = torch.load(self.motion_file, map_location="cpu", weights_only=False)
        if not torch.is_tensor(motion):
            raise TypeError(f"Expected a bare torch.Tensor in {self.motion_file}, got {type(motion)}.")
        if motion.ndim != 2:
            raise ValueError(f"Expected a (T, raw) tensor, got shape {tuple(motion.shape)}.")

        # raw = 26 + 2 * ND + 14 * NB, so NB follows from the tensor width.
        nd = self.num_dof
        residual = motion.shape[1] - 26 - 2 * nd
        if residual <= 0 or residual % 14 != 0:
            raise ValueError(
                f"Tensor width {motion.shape[1]} is not consistent with num_dof={nd}: expected"
                f" 26 + 2*{nd} + 14*NB for an integer NB."
            )
        self.num_bodies = residual // 14

        if self.frame_range is not None:
            motion = motion[self.frame_range[0] - 1 : self.frame_range[1]]
        motion = motion.to(torch.float32).to(self.device)
        self.raw = motion

        self.motion_base_poss = motion[:, 0:3]
        self.motion_base_rots = motion[:, 3:7][:, [3, 0, 1, 2]]  # convert to wxyz
        self.motion_base_lin_vels = motion[:, 7:10]
        self.motion_base_ang_vels = motion[:, 10:13]
        self.motion_dof_poss = motion[:, 13 : 13 + nd]
        self.motion_dof_vels = motion[:, 13 + nd : 13 + 2 * nd]

        obj_start = 13 + 2 * nd
        self.motion_object_poss = motion[:, obj_start : obj_start + 3]
        self.motion_object_rots = motion[:, obj_start + 3 : obj_start + 7][:, [3, 0, 1, 2]]  # convert to wxyz
        self.motion_object_lin_vels = motion[:, obj_start + 7 : obj_start + 10]
        self.motion_object_ang_vels = motion[:, obj_start + 10 : obj_start + 13]

        # Kept only for the post-bake diagnostics; the final reference regenerates these.
        body_start = 26 + 2 * nd
        nb = self.num_bodies
        self.source_body_poss = motion[:, body_start : body_start + nb * 3].view(-1, nb, 3)
        self.source_body_lin_vels = motion[:, body_start + nb * 7 : body_start + nb * 10].view(-1, nb, 3)

        # Per-body contact flags trail the body block. 6 = left_hand_link, 11 = right_hand_link:
        # verified against the object trajectory (on at grasp, off together at set-down).
        contact_block = motion[:, body_start + 13 * nb : body_start + 14 * nb]
        self.motion_contacts = contact_block[:, CONTACT_SOURCE_INDEXES]

        self.motion_stance = None
        if nb > max(toe for _, toe, _ in STANCE_CHANNELS) and all(
            torch.equal(contact_block[:, foot], contact_block[:, toe]) for foot, toe, _ in STANCE_CHANNELS
        ):
            self.motion_stance = contact_block[:, [foot for foot, _, _ in STANCE_CHANNELS]].clone()
            share = ", ".join(f"{n} {v * 100:.1f}%" for n, v in zip(STANCE_NAMES, self.motion_stance.mean(0).tolist()))
            print(f"[STANCE]: per-foot stance labels found ({share} of frames); writing them as 'stance'")
        else:
            print("[STANCE]: no per-foot stance labels in this file (foot and toe-sphere columns differ); no 'stance' key")

        quat_norm = self.motion_base_rots.norm(dim=-1)
        if not torch.allclose(quat_norm, torch.ones_like(quat_norm), atol=1e-3):
            raise ValueError(f"Root quaternions are not unit norm (min {quat_norm.min()}, max {quat_norm.max()}).")

        obj_quat_norm = self.motion_object_rots.norm(dim=-1)
        if not torch.allclose(obj_quat_norm, torch.ones_like(obj_quat_norm), atol=1e-3):
            raise ValueError(
                f"Object quaternions are not unit norm (min {obj_quat_norm.min()}, max {obj_quat_norm.max()})."
            )

        self.output_frames = motion.shape[0]
        self.duration = (self.output_frames - 1) * self.output_dt
        print(
            f"Motion loaded ({self.motion_file}), duration: {self.duration} sec, frames: {self.output_frames},"
            f" bodies: {self.num_bodies}, dof: {nd}"
        )

    def get_next_state(self):
        """Gets the next state of the motion."""
        state = (
            self.motion_base_poss[self.current_idx : self.current_idx + 1],
            self.motion_base_rots[self.current_idx : self.current_idx + 1],
            self.motion_base_lin_vels[self.current_idx : self.current_idx + 1],
            self.motion_base_ang_vels[self.current_idx : self.current_idx + 1],
            self.motion_dof_poss[self.current_idx : self.current_idx + 1],
            self.motion_dof_vels[self.current_idx : self.current_idx + 1],
            self.motion_object_poss[self.current_idx : self.current_idx + 1],
            self.motion_object_rots[self.current_idx : self.current_idx + 1],
            self.motion_object_lin_vels[self.current_idx : self.current_idx + 1],
            self.motion_object_ang_vels[self.current_idx : self.current_idx + 1],
            self.motion_contacts[self.current_idx : self.current_idx + 1],
        )
        self.last_idx = self.current_idx
        self.current_idx += 1
        reset_flag = False
        if self.current_idx >= self.output_frames:
            self.current_idx = 0
            reset_flag = True
        return state, reset_flag


def resolve_joint_indexes(robot_joint_names: list[str], aliases: list[tuple[str, ...]]) -> list[int]:
    """Maps each source DOF column onto an index into the spawned robot's joint order."""
    indexes = []
    unresolved = []
    for row in aliases:
        for name in row:
            if name in robot_joint_names:
                indexes.append(robot_joint_names.index(name))
                break
        else:
            unresolved.append(row)
    if unresolved:
        raise RuntimeError(
            "Could not map every source DOF onto the spawned robot.\n"
            f"  unresolved: {unresolved}\n"
            f"  robot.joint_names: {robot_joint_names}\n"
            "The installed booster_assets K1 model does not match the one this motion was retargeted against."
        )
    if len(set(indexes)) != len(indexes):
        raise RuntimeError(f"Source DOFs mapped onto duplicate robot joints: {indexes}")
    return indexes



class Mp4Writer:
    """Small streaming MP4 writer so we never keep the full video in RAM."""

    def __init__(self, path: str, fps: int):
        try:
            import imageio.v2 as imageio
        except ImportError as exc:
            raise RuntimeError(
                "MP4 output requires imageio and imageio-ffmpeg. Install them with:\n"
                "  pip install imageio imageio-ffmpeg"
            ) from exc

        self.path = path
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        self._writer = imageio.get_writer(
            path,
            fps=fps,
            codec="libx264",
            quality=8,
            macro_block_size=None,
        )

    def append(self, rgb: torch.Tensor):
        """Append one HxWx3/4 torch RGB(A) frame."""
        frame = rgb.detach().cpu().numpy()
        if frame.shape[-1] == 4:
            frame = frame[..., :3]

        # Current Isaac Lab RGB camera output is uint8, but keep this robust to
        # float renderers as well.
        if frame.dtype != np.uint8:
            if np.issubdtype(frame.dtype, np.floating) and frame.max() <= 1.0:
                frame = frame * 255.0
            frame = np.clip(frame, 0, 255).astype(np.uint8)

        self._writer.append_data(frame)

    def close(self):
        if self._writer is not None:
            print(f"[INFO]: Finalizing video: {self.path}...", flush=True)
            self._writer.close()
            self._writer = None
        print(f"[INFO]: Video saved to {self.path}", flush=True)


def run_simulator(sim: sim_utils.SimulationContext, scene: InteractiveScene):
    """Runs the simulation loop."""
    # Load motion
    motion = InterMimicMotionLoader(
        motion_file=args_cli.input_file,
        input_fps=args_cli.input_fps,
        output_fps=args_cli.output_fps,
        num_dof=args_cli.num_dof,
        device=sim.device,
        frame_range=args_cli.frame_range,
    )

    # Extract scene entities
    robot = scene["robot"]
    obj: RigidObject = scene["object"]
    camera: Camera | None = scene["camera"] if args_cli.video is not None else None
    video_writer = Mp4Writer(args_cli.video, args_cli.output_fps) if args_cli.video is not None else None
    camera_anchor_z = None  # standing root height, captured on the first rendered frame
    camera_offset = torch.tensor(args_cli.camera_offset, device=sim.device, dtype=torch.float32).unsqueeze(0)
    camera_lookat_offset = torch.tensor(
        args_cli.camera_lookat_offset, device=sim.device, dtype=torch.float32
    ).unsqueeze(0)

    robot_joint_indexes = resolve_joint_indexes(list(robot.joint_names), K1_DOF_ALIASES)
    foot_ids = [robot.body_names.index(name) for name in ("left_foot_link", "right_foot_link")]
    palm_ids = [robot.body_names.index(name) for name in PALM_BODY_NAMES]
    palm_offsets = torch.tensor(palm_offset_vectors(cli_palm_offset()), device=sim.device, dtype=torch.float32)
    palm_markers = None
    if args_cli.show_contact_points:
        from isaaclab.markers import VisualizationMarkers, VisualizationMarkersCfg

        palm_markers = VisualizationMarkers(
            VisualizationMarkersCfg(
                prim_path="/Visuals/ContactPoints",
                markers={
                    # palm keypoint: grey while the reference reports no contact, green while it does
                    "free": sim_utils.SphereCfg(
                        radius=0.015,
                        visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.65, 0.65, 0.65)),
                    ),
                    "contact": sim_utils.SphereCfg(
                        radius=0.030,
                        visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.1, 0.9, 0.2)),
                    ),
                    # the observation's contact target, rigidly attached to the object
                    "target": sim_utils.SphereCfg(
                        radius=0.022,
                        visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(1.0, 0.45, 0.0)),
                    ),
                },
            )
        )
    stand_start = None
    lead_frames = 0
    lead_feet_ref = None
    feet_ref = None  # feet on the last clip frame, captured in the loop
    prev_root = None
    # Lead-in first: it shifts every later frame index, including the one append_stand_transition reports.
    if args_cli.start_s > 0:
        lead_frames, lead_feet_ref = prepend_start_transition(
            motion, robot, robot_joint_indexes, sim, scene, foot_ids
        )
    if args_cli.stand_s > 0:
        if args_cli.end_mode == "settle":
            stand_start = append_settle_transition(motion, robot, robot_joint_indexes, sim, scene, foot_ids)
        else:
            stand_start = append_stand_transition(motion, robot, robot_joint_indexes)
    settle = args_cli.end_mode == "settle" and stand_start is not None
    global SETTLE_SOLE_CORNERS
    SETTLE_SOLE_CORNERS = SETTLE_SOLE_CORNERS.to(sim.device)
    last_root = last_obj = prev_obj = None  # clip's last root and object pose (settle mode), captured in the loop
    contact_targets = None
    if args_cli.show_contact_points:
        contact_targets = precompute_contact_targets(motion, robot, sim, scene, palm_ids, palm_offsets)
    if args_cli.object_physics:
        setup_object_physics(obj, scene, motion)
    prev = None  # previous frame's robot state, interpolated across the physics substeps
    if len(robot.joint_names) != len(robot_joint_indexes):
        print(
            f"[WARN]: the robot has {len(robot.joint_names)} joints but the motion only drives"
            f" {len(robot_joint_indexes)}. The rest stay at their default pose."
        )
    missing_bodies = [name for name in TASK_BODY_NAMES if name not in robot.body_names]
    if missing_bodies:
        print(
            f"[WARN]: the spawned model is missing bodies the shipped K1 tasks track: {missing_bodies}.\n"
            f"[WARN]: robot.body_names = {list(robot.body_names)}\n"
            "[WARN]: the npz will still be written, but MotionLoader will raise on these names at train time."
        )

    # ------- data logger -------------------------------------------------------
    log = {
        "fps": [args_cli.output_fps],
        "joint_pos": [],
        "joint_vel": [],
        "body_pos_w": [],
        "body_quat_w": [],
        "body_lin_vel_w": [],
        "body_ang_vel_w": [],
        "object_pos_w": [],
        "object_quat_w": [],
        "object_lin_vel_w": [],
        "object_ang_vel_w": [],
        "contact": [],
        "joint_names": np.array(robot.joint_names),
        "body_names": np.array(robot.body_names),
        "contact_names": np.array(CONTACT_NAMES),
        **({"stance": [], "stance_names": np.array(STANCE_NAMES)} if motion.motion_stance is not None else {}),
        "object_name": np.array(args_cli.object),
    }
    file_saved = False
    # --------------------------------------------------------------------------

    # Simulation loop
    while simulation_app.is_running():
        (
            (
                motion_base_pos,
                motion_base_rot,
                motion_base_lin_vel,
                motion_base_ang_vel,
                motion_dof_pos,
                motion_dof_vel,
                motion_object_pos,
                motion_object_rot,
                motion_object_lin_vel,
                motion_object_ang_vel,
                motion_contact,
            ),
            reset_flag,
        ) = motion.get_next_state()

        if args_cli.object_physics:
            # Kinematic robot, physical object: sweep the robot from the previous frame's pose to this one across
            # the substeps (re-written every substep so gravity and the PD never act on it), and only step physics.
            cur = (motion_base_pos, motion_base_rot, motion_dof_pos)
            if prev is None:
                prev = cur
            for k in range(1, args_cli.substeps + 1):
                a = k / args_cli.substeps
                q0, q1 = prev[1], cur[1]
                q1 = torch.where((q0 * q1).sum(-1, keepdim=True) < 0, -q1, q1)
                root_states = robot.data.default_root_state.clone()
                root_states[:, :3] = (1 - a) * prev[0] + a * cur[0]
                root_states[:, :2] += scene.env_origins[:, :2]
                root_states[:, 3:7] = torch.nn.functional.normalize((1 - a) * q0 + a * q1, dim=-1)
                root_states[:, 7:10] = motion_base_lin_vel
                root_states[:, 10:] = motion_base_ang_vel
                robot.write_root_state_to_sim(root_states)
                joint_pos = robot.data.default_joint_pos.clone()
                joint_vel = robot.data.default_joint_vel.clone()
                joint_pos[:, robot_joint_indexes] = (1 - a) * prev[2] + a * cur[2]
                joint_vel[:, robot_joint_indexes] = motion_dof_vel
                if args_cli.robot_drive == "teleport" or prev is cur:
                    robot.write_joint_state_to_sim(joint_pos, joint_vel)
                robot.set_joint_position_target(joint_pos)
                robot.set_joint_velocity_target(joint_vel)
                robot.write_data_to_sim()
                sim.step(render=False)
                scene.update(sim.get_physics_dt())
            prev = cur

        # set root state
        root_states = robot.data.default_root_state.clone()
        root_states[:, :3] = motion_base_pos
        root_states[:, :2] += scene.env_origins[:, :2]
        root_states[:, 3:7] = motion_base_rot
        root_states[:, 7:10] = motion_base_lin_vel
        root_states[:, 10:] = motion_base_ang_vel
        # write_root_state_to_sim reads [:7] as the link-frame pose and [7:] as the
        # center-of-mass velocity, which is the source file's convention exactly.
        robot.write_root_state_to_sim(root_states)

        # set joint state
        joint_pos = robot.data.default_joint_pos.clone()
        joint_vel = robot.data.default_joint_vel.clone()
        joint_pos[:, robot_joint_indexes] = motion_dof_pos
        joint_vel[:, robot_joint_indexes] = motion_dof_vel
        # With --robot_drive pd the joints are left where the actuators put them (after frame 0).
        if not (args_cli.object_physics and args_cli.robot_drive == "pd" and log["joint_pos"]):
            robot.write_joint_state_to_sim(joint_pos, joint_vel)

        if stand_start is not None or lead_frames:
            frame = len(log["joint_pos"])  # index of the frame being written
            # Which clip frame's feet this synthetic frame has to stand on: the clip's first for the lead-in,
            # its last for the stand transition, and neither for the clip itself.
            synthetic_ref = None
            if frame < lead_frames:
                synthetic_ref = lead_feet_ref
            elif stand_start is not None and frame >= stand_start:
                synthetic_ref = feet_ref
            if synthetic_ref is not None:
                # Root placement for the synthetic transition: FK with the guessed root, then shift it so the lower
                # foot is at the height the reference frame's feet had and the feet midpoint does not drift.
                sim.physics_sim_view.update_articulations_kinematic()
                robot.update(0.0)
                feet = robot.data.body_pos_w[0, foot_ids]
                shift = torch.zeros(3, device=sim.device)
                pin = getattr(motion, "settle_pin", None) if frame >= (stand_start or 0) and settle else None
                if pin is not None:
                    # Settle: the stance foot stays where the clip left it in xy (the other one moves), and the root
                    # height keeps that foot's lowest sole corner on the floor -- pinning the foot link's height
                    # instead would leave a foot that flattens from a rolled edge hovering. The moving foot is not
                    # used: it starts mid-step, tipped toe-down, and would lift the stance foot off the ground.
                    shift[:2] = synthetic_ref[pin, :2] - feet[pin, :2]
                    corners = robot.data.body_pos_w[0, foot_ids][:, None, :] + quat_apply(
                        robot.data.body_quat_w[0, foot_ids][:, None, :].expand(2, 4, 4), SETTLE_SOLE_CORNERS
                    )
                    shift[2] = -corners[pin, :, 2].min()
                else:
                    shift[:2] = synthetic_ref[:, :2].mean(0) - feet[:, :2].mean(0)
                    shift[2] = synthetic_ref[:, 2].min() - feet[:, 2].min()
                root_states[:, :3] += shift
                if prev_root is not None:
                    dt = 1.0 / args_cli.output_fps
                    root_states[:, 7:10] = (root_states[:, :3] - prev_root[:, :3]) / dt
                    dq = quat_mul(root_states[:, 3:7], quat_conjugate(prev_root[:, 3:7]))
                    dq = torch.where(dq[:, :1] < 0, -dq, dq)
                    root_states[:, 10:] = 2.0 * dq[:, 1:] / dt
                robot.write_root_state_to_sim(root_states)
                robot.write_joint_state_to_sim(joint_pos, joint_vel)
            prev_root = root_states.clone()

        if settle and len(log["joint_pos"]) >= stand_start and last_root is not None:
            # Carry the object rigidly with the trunk: T_obj = T_root_now * T_root_last^-1 * T_obj_last.
            root_pos_now = root_states[0, :3] - torch.cat([scene.env_origins[0, :2], scene.env_origins.new_zeros(1)])
            rel_q = quat_mul(root_states[:1, 3:7], quat_conjugate(last_root[1][None]))
            motion_object_pos = (root_pos_now + quat_apply(rel_q, (last_obj[0] - last_root[0])[None])[0])[None]
            motion_object_rot = quat_mul(rel_q, last_obj[1][None])
            if prev_obj is not None:
                dt = 1.0 / args_cli.output_fps
                motion_object_lin_vel = (motion_object_pos - prev_obj[0]) / dt
                dq = quat_mul(motion_object_rot, quat_conjugate(prev_obj[1]))
                dq = torch.where(dq[:, :1] < 0, -dq, dq)
                motion_object_ang_vel = 2.0 * dq[:, 1:] / dt
            prev_obj = (motion_object_pos.clone(), motion_object_rot.clone())

        # set object state (kinematic replay, same convention as the robot root above)
        if not args_cli.object_physics:
            object_states = obj.data.default_root_state.clone()
            object_states[:, :3] = motion_object_pos
            object_states[:, :2] += scene.env_origins[:, :2]
            object_states[:, 3:7] = motion_object_rot
            object_states[:, 7:10] = motion_object_lin_vel
            object_states[:, 10:] = motion_object_ang_vel
            obj.write_root_state_to_sim(object_states)

        if palm_markers is not None:
            # Refresh the link poses the markers hang off. Under --robot_drive pd the physics step already did.
            if not (args_cli.object_physics and args_cli.robot_drive == "pd"):
                sim.physics_sim_view.update_articulations_kinematic()
            robot.update(0.0)
            palms = robot.data.body_pos_w[0, palm_ids] + quat_apply(robot.data.body_quat_w[0, palm_ids], palm_offsets)
            # The target rides the object, so it is mapped through whatever pose the object actually has now.
            if args_cli.object_physics:
                obj_pos_now, obj_quat_now = obj.data.root_pos_w[0], obj.data.root_quat_w[0]
            else:
                obj_pos_now = motion_object_pos[0] + scene.env_origins[0]
                obj_quat_now = motion_object_rot[0]
            frame_index = min(len(log["joint_pos"]), contact_targets.shape[0] - 1)
            targets = obj_pos_now + quat_apply(
                obj_quat_now.expand(contact_targets.shape[1], 4), contact_targets[frame_index]
            )
            palm_markers.visualize(
                translations=torch.cat([palms, targets], dim=0),
                marker_indices=torch.cat([
                    (motion_contact[0] > 0.5).long(),
                    torch.full((targets.shape[0],), 2, dtype=torch.long, device=sim.device),
                ]),
            )

        # Move the offscreen camera with the robot before rendering this frame.
        # The camera itself is a real Isaac Lab Camera sensor; this works in
        # --headless mode because --video forces enable_cameras=True above.
        if camera is not None:
            # Follow the root horizontally only. Tying the look-at height to the root as well makes the frame
            # dive whenever the robot squats -- which is most of a pick-up motion -- and crops the feet.
            # The height is pinned to the standing root height of the first frame instead.
            if camera_anchor_z is None:
                camera_anchor_z = root_states[0, 2].item()
                if args_cli.camera_view == "front":
                    # Rotate the offset by the frame-0 heading only, so the camera does not swing as the robot turns.
                    w, x, y, z = root_states[0, 3:7].tolist()
                    yaw = np.arctan2(2 * (w * z + x * y), 1 - 2 * (y * y + z * z))
                    ox, oy, oz = (2.2, 0.0, 0.6) if tuple(args_cli.camera_offset) == (1.8, 1.8, 0.6) else args_cli.camera_offset
                    camera_offset = torch.tensor(
                        [[ox * np.cos(yaw) - oy * np.sin(yaw), ox * np.sin(yaw) + oy * np.cos(yaw), oz]],
                        device=sim.device, dtype=torch.float32,
                    )  # fmt: skip
            target = root_states[:, :3] + camera_lookat_offset
            target[:, 2] = camera_anchor_z + camera_lookat_offset[0, 2]
            eye = target + camera_offset
            camera.set_world_poses_from_view(eye, target)

        # Kinematic replay only: render the state we just wrote; do not advance physics.
        sim.render()
        scene.update(sim.get_physics_dt())

        if camera is not None and video_writer is not None:
            video_writer.append(camera.data.output["rgb"][0])

        # Keep the interactive viewport useful as well.
        if sim.has_gui():
            pos_lookat = root_states[0, :3].cpu().numpy()
            sim.set_camera_view(
                pos_lookat + np.asarray(args_cli.camera_offset),
                pos_lookat + np.asarray(args_cli.camera_lookat_offset),
            )

        if stand_start is not None and len(log["joint_pos"]) == stand_start - 1 and feet_ref is None:
            sim.physics_sim_view.update_articulations_kinematic()
            robot.update(0.0)
            feet_ref = robot.data.body_pos_w[0, foot_ids].clone()
            if settle:
                origin = torch.cat([scene.env_origins[0, :2], scene.env_origins.new_zeros(1)])
                last_root = (root_states[0, :3] - origin, root_states[0, 3:7].clone())
                last_obj = (motion_object_pos[0].clone(), motion_object_rot[0].clone())
                prev_obj = (motion_object_pos.clone(), motion_object_rot.clone())
        if not file_saved:
            log["joint_pos"].append(robot.data.joint_pos[0, :].cpu().numpy().copy())
            log["joint_vel"].append(robot.data.joint_vel[0, :].cpu().numpy().copy())
            log["body_pos_w"].append(robot.data.body_pos_w[0, :].cpu().numpy().copy())
            log["body_quat_w"].append(robot.data.body_quat_w[0, :].cpu().numpy().copy())
            log["body_lin_vel_w"].append(robot.data.body_lin_vel_w[0, :].cpu().numpy().copy())
            log["body_ang_vel_w"].append(robot.data.body_ang_vel_w[0, :].cpu().numpy().copy())
            if args_cli.object_physics:
                log["object_pos_w"].append((obj.data.root_pos_w[0] - scene.env_origins[0]).cpu().numpy().copy())
                log["object_quat_w"].append(obj.data.root_quat_w[0].cpu().numpy().copy())
                log["object_lin_vel_w"].append(obj.data.root_lin_vel_w[0].cpu().numpy().copy())
                log["object_ang_vel_w"].append(obj.data.root_ang_vel_w[0].cpu().numpy().copy())
                log.setdefault("ref_object_pos_w", []).append(motion_object_pos[0].cpu().numpy().copy())
            else:
                log["object_pos_w"].append(motion_object_pos[0, :].cpu().numpy().copy())
                log["object_quat_w"].append(motion_object_rot[0, :].cpu().numpy().copy())
                log["object_lin_vel_w"].append(motion_object_lin_vel[0, :].cpu().numpy().copy())
                log["object_ang_vel_w"].append(motion_object_ang_vel[0, :].cpu().numpy().copy())
            log["contact"].append(motion_contact[0, :].cpu().numpy().copy())
            if motion.motion_stance is not None:
                log["stance"].append(motion.motion_stance[motion.last_idx].cpu().numpy().copy())

        if reset_flag and not file_saved:
            file_saved = True
            for k in (
                "joint_pos",
                "joint_vel",
                "body_pos_w",
                "body_quat_w",
                "body_lin_vel_w",
                "body_ang_vel_w",
                "object_pos_w",
                "object_quat_w",
                "object_lin_vel_w",
                "object_ang_vel_w",
                "contact",
                *(("stance",) if motion.motion_stance is not None else ()),
            ):
                log[k] = np.stack(log[k], axis=0)

            report_bake_quality(log, motion, robot)
            if args_cli.show_contact_points:
                report_contact_points(log, robot)
            if args_cli.object_physics:
                ref_obj = np.stack(log.pop("ref_object_pos_w"))
                sim_obj = log["object_pos_w"]
                err = np.linalg.norm(sim_obj - ref_obj, axis=-1)
                z0 = ref_obj[0, 2]
                lifted = ref_obj[:, 2] > z0 + 0.10
                print(f"[PHYSICS]: object max lift  sim {sim_obj[:, 2].max() - z0:+.3f} m   ref {ref_obj[:, 2].max() - z0:+.3f} m")
                print(f"[PHYSICS]: object error     mean {err.mean():.3f} m   max {err.max():.3f} m   final {err[-1]:.3f} m")
                if lifted.any():
                    print(f"[PHYSICS]: carried (within 10 cm while ref lifted): {(err[lifted] < 0.10).mean() * 100:.0f}%")
            np.savez(f"{args_cli.output_name}", **log)
            print(f"[INFO]: Motion saved to {args_cli.output_name}")
            if video_writer is not None:
                video_writer.close()
            return


def prepend_start_transition(
    motion: "InterMimicMotionLoader", robot, robot_joint_indexes: list[int], sim, scene, foot_ids: list[int]
) -> tuple[int, "torch.Tensor"]:
    """Prepend a standing-pose -> clip-first-pose lead-in; returns (frames added, feet of the clip's first frame).

    The mirror of :func:`append_stand_transition`. Joints: cubic Hermite from (q_stand, 0) to the clip's first
    (q, v), so the lead-in starts at rest and arrives with the clip's own joint velocity. Root orientation: slerp
    (smoothstep-timed) from upright-at-the-clip's-initial-heading into the clip's first rotation. Root position is
    a placeholder; the bake loop places it from the feet each frame, against the returned reference. The object is
    held at its first pose and the hand contact labels are cleared.
    """
    fps = motion.output_fps
    steps = max(int(round(args_cli.start_s * fps)), 1)
    duration = steps / fps
    dev = motion.motion_dof_poss.device

    # Feet of the clip's first frame: what the lead-in has to stand on. FK it before the arrays are extended.
    root_states = robot.data.default_root_state.clone()
    root_states[:, :3] = motion.motion_base_poss[0]
    root_states[:, :2] += scene.env_origins[:, :2]
    root_states[:, 3:7] = motion.motion_base_rots[0]
    root_states[:, 7:] = 0.0
    robot.write_root_state_to_sim(root_states)
    joint_pos = robot.data.default_joint_pos.clone()
    joint_pos[:, robot_joint_indexes] = motion.motion_dof_poss[0]
    robot.write_joint_state_to_sim(joint_pos, torch.zeros_like(joint_pos))
    sim.physics_sim_view.update_articulations_kinematic()
    robot.update(0.0)
    feet_ref = robot.data.body_pos_w[0, foot_ids].clone()

    q1, v1 = motion.motion_dof_poss[0], motion.motion_dof_vels[0]
    if args_cli.start_pose == "prepare":
        q0 = torch.tensor(K1_PREPARE_POSE, device=dev, dtype=q1.dtype)
    else:
        q0 = robot.data.default_joint_pos[0, robot_joint_indexes].to(dev)
    # u = 0 .. (steps-1)/steps: the lead-in's first frame is exactly the standing pose, and frame `steps` of the
    # output is the clip's own first frame, so u = 1 is never emitted twice.
    u = (torch.arange(0, steps, device=dev, dtype=torch.float32) / steps).unsqueeze(-1)
    h00, h01, h11 = 2 * u**3 - 3 * u**2 + 1, -2 * u**3 + 3 * u**2, u**3 - u**2
    d00, d01, d11 = 6 * u**2 - 6 * u, -6 * u**2 + 6 * u, 3 * u**2 - 2 * u
    dof_pos = h00 * q0 + h01 * q1 + h11 * duration * v1
    dof_vel = (d00 * q0 + d01 * q1 + d11 * duration * v1) / duration

    rot1 = motion.motion_base_rots[0]
    w, x, y, z = rot1.tolist()
    yaw = math.atan2(2 * (w * z + x * y), 1 - 2 * (y * y + z * z))
    rot0 = torch.tensor([math.cos(yaw / 2), 0.0, 0.0, math.sin(yaw / 2)], device=dev)
    if torch.dot(rot0, rot1) < 0:
        rot0 = -rot0
    s_t = 3 * u**2 - 2 * u**3
    angle = torch.acos(torch.clamp(torch.dot(rot0, rot1), -1.0, 1.0))
    if angle < 1e-6:
        rots = rot0.expand(steps, 4).clone()
    else:
        rots = (torch.sin((1 - s_t) * angle) * rot0 + torch.sin(s_t * angle) * rot1) / torch.sin(angle)

    def prepend(name: str, head: torch.Tensor):
        cur = getattr(motion, name)
        setattr(motion, name, torch.cat([head.to(cur.dtype), cur], dim=0))

    prepend("motion_dof_poss", dof_pos)
    prepend("motion_dof_vels", dof_vel)
    prepend("motion_base_rots", rots)
    prepend("motion_base_poss", motion.motion_base_poss[:1].expand(steps, 3))
    prepend("motion_base_lin_vels", torch.zeros(steps, 3, device=dev))
    prepend("motion_base_ang_vels", torch.zeros(steps, 3, device=dev))
    prepend("motion_object_poss", motion.motion_object_poss[:1].expand(steps, 3))
    prepend("motion_object_rots", motion.motion_object_rots[:1].expand(steps, 4))
    prepend("motion_object_lin_vels", torch.zeros(steps, 3, device=dev))
    prepend("motion_object_ang_vels", torch.zeros(steps, 3, device=dev))
    prepend("motion_contacts", torch.zeros(steps, motion.motion_contacts.shape[1], device=dev))
    if motion.motion_stance is not None:
        prepend("motion_stance", torch.ones(steps, motion.motion_stance.shape[1], device=dev))  # stood on both feet
    motion.output_frames += steps
    motion.lead_frames = steps
    print(
        f"[START]: prepended {steps} frames ({duration:.2f} s) from the '{args_cli.start_pose}' standing pose to the"
        f" clip's first pose; max joint change {(q1 - q0).abs().max().item():.3f} rad, clip start joint speed"
        f" {v1.abs().max().item():.3f} rad/s",
        flush=True,
    )
    return steps, feet_ref


def precompute_contact_targets(motion, robot, sim, scene, palm_ids, palm_offsets) -> torch.Tensor:
    """Per-frame contact target for each hand, in the object's own frame: (frames, 2, 3).

    This is the quantity the HOI observation carries. While the reference reports contact it is the live palm
    keypoint expressed in the object frame. While it does not, it holds the value the palm will have at the
    *start of the next* contact window, so the target is an aim point the hand can converge on during the
    approach; after the final window it holds that window's last value.

    Needs a forward-kinematics pass over the whole clip, which the main loop cannot do because it only ever
    sees one frame at a time. No physics is stepped and nothing is rendered, so the pass is cheap.
    """
    n = motion.output_frames
    dev = sim.device
    palms = torch.zeros(n, len(palm_ids), 3, device=dev)
    joint_pos_full = robot.data.default_joint_pos.clone()
    robot_joint_indexes = resolve_joint_indexes(list(robot.joint_names), K1_DOF_ALIASES)
    for f in range(n):
        root_states = robot.data.default_root_state.clone()
        root_states[:, :3] = motion.motion_base_poss[f]
        root_states[:, :2] += scene.env_origins[:, :2]
        root_states[:, 3:7] = motion.motion_base_rots[f]
        root_states[:, 7:] = 0.0
        robot.write_root_state_to_sim(root_states)
        joint_pos = joint_pos_full.clone()
        joint_pos[:, robot_joint_indexes] = motion.motion_dof_poss[f]
        robot.write_joint_state_to_sim(joint_pos, torch.zeros_like(joint_pos))
        sim.physics_sim_view.update_articulations_kinematic()
        robot.update(0.0)
        palms[f] = robot.data.body_pos_w[0, palm_ids] + quat_apply(robot.data.body_quat_w[0, palm_ids], palm_offsets)

    # Into the reference object's frame. Both sides carry the env origin, so it cancels; subtract it anyway.
    obj_pos = motion.motion_object_poss + scene.env_origins[0]
    obj_quat = motion.motion_object_rots
    rel = palms - obj_pos[:, None, :]
    conj = quat_conjugate(obj_quat)[:, None, :].expand(-1, palms.shape[1], -1)
    local = quat_apply(conj, rel)

    contact = motion.motion_contacts > 0.5
    target = local.clone()
    for side in range(palms.shape[1]):
        frames = torch.nonzero(contact[:, side]).flatten()
        if frames.numel() == 0:
            print(f"[TARGET]: hand {side} never contacts; its target is the live palm point.", flush=True)
            continue
        # First frame of each contact run, and the last frame of the final run.
        starts = frames[torch.cat([torch.ones(1, dtype=torch.bool, device=dev), frames[1:] != frames[:-1] + 1])]
        for f in range(n):
            if contact[f, side]:
                continue
            ahead = starts[starts > f]
            target[f, side] = local[ahead[0] if ahead.numel() else frames[-1], side]
        runs = starts.numel()
        step = (target[1:, side] - target[:-1, side]).norm(dim=-1)
        worst = int(step.argmax())
        print(
            f"[TARGET]: hand {side}: {frames.numel()} contact frames in {runs} window(s);"
            f" target held from the next window on {int((~contact[:, side]).sum())} frames;"
            f" largest frame-to-frame jump {step.max().item() * 100:.1f} cm at frame {worst}",
            flush=True,
        )
    return target


def append_stand_transition(motion: "InterMimicMotionLoader", robot, robot_joint_indexes: list[int]) -> int:
    """Extend the loaded motion with a last-pose -> default-standing-pose transition; returns its first frame.

    Joints: cubic Hermite from (q_end, v_end) to (q_stand, 0) over the transition, so the joint velocity is continuous
    with the clip and the transition ends at rest. Root orientation: slerp (smoothstep-timed) to upright with the clip's
    final heading. Root position is a placeholder here; the bake loop places it from the feet each frame. The object
    is held at its final pose and the hand contact labels are cleared.
    """
    fps = motion.output_fps
    n = motion.output_frames
    steps = max(int(round(args_cli.stand_s * fps)), 1)
    duration = steps / fps
    dev = motion.motion_dof_poss.device
    q0, v0 = motion.motion_dof_poss[-1], motion.motion_dof_vels[-1]
    if args_cli.stand_pose == "prepare":
        q1 = torch.tensor(K1_PREPARE_POSE, device=dev, dtype=q0.dtype)
    else:
        q1 = robot.data.default_joint_pos[0, robot_joint_indexes].to(dev)
    u = (torch.arange(1, steps + 1, device=dev, dtype=torch.float32) / steps).unsqueeze(-1)
    h00, h10, h01 = 2 * u**3 - 3 * u**2 + 1, u**3 - 2 * u**2 + u, -2 * u**3 + 3 * u**2
    d00, d10, d01 = 6 * u**2 - 6 * u, 3 * u**2 - 4 * u + 1, -6 * u**2 + 6 * u
    dof_pos = h00 * q0 + h10 * duration * v0 + h01 * q1
    dof_vel = (d00 * q0 + d10 * duration * v0 + d01 * q1) / duration

    rot0 = motion.motion_base_rots[-1]
    w, x, y, z = rot0.tolist()
    yaw = math.atan2(2 * (w * z + x * y), 1 - 2 * (y * y + z * z))
    rot1 = torch.tensor([math.cos(yaw / 2), 0.0, 0.0, math.sin(yaw / 2)], device=dev)
    if torch.dot(rot0, rot1) < 0:
        rot1 = -rot1
    s = 3 * u**2 - 2 * u**3
    angle = torch.acos(torch.clamp(torch.dot(rot0, rot1), -1.0, 1.0))
    if angle < 1e-6:
        rots = rot0.expand(steps, 4).clone()
    else:
        rots = (torch.sin((1 - s) * angle) * rot0 + torch.sin(s * angle) * rot1) / torch.sin(angle)

    def extend(name: str, tail: torch.Tensor):
        setattr(motion, name, torch.cat([getattr(motion, name), tail.to(getattr(motion, name).dtype)], dim=0))

    extend("motion_dof_poss", dof_pos)
    extend("motion_dof_vels", dof_vel)
    extend("motion_base_rots", rots)
    extend("motion_base_poss", motion.motion_base_poss[-1:].expand(steps, 3))
    extend("motion_base_lin_vels", torch.zeros(steps, 3, device=dev))
    extend("motion_base_ang_vels", torch.zeros(steps, 3, device=dev))
    extend("motion_object_poss", motion.motion_object_poss[-1:].expand(steps, 3))
    extend("motion_object_rots", motion.motion_object_rots[-1:].expand(steps, 4))
    extend("motion_object_lin_vels", torch.zeros(steps, 3, device=dev))
    extend("motion_object_ang_vels", torch.zeros(steps, 3, device=dev))
    extend("motion_contacts", torch.zeros(steps, motion.motion_contacts.shape[1], device=dev))
    if motion.motion_stance is not None:
        extend("motion_stance", torch.ones(steps, motion.motion_stance.shape[1], device=dev))  # stood on both feet
    motion.output_frames = n + steps
    print(
        f"[STAND]: appended {steps} frames ({duration:.2f} s) from the last pose to the '{args_cli.stand_pose}' standing pose;"
        f" max joint change {(q1 - q0).abs().max().item():.3f} rad, clip end joint speed {v0.abs().max().item():.3f} rad/s",
        flush=True,
    )
    return n


# Sole corners in each foot link's frame (left, right), from meshes/{Left,Right}_Foot.STL: the flat sole is at
# z = -0.0382; toe-outer, toe-inner, heel-outer, heel-inner, outer = +y on the left foot.
_SOLE_LEFT = [[0.0995, 0.04, -0.0382], [0.0995, -0.04, -0.0382], [-0.0657, 0.04, -0.0382], [-0.0657, -0.04, -0.0382]]
SETTLE_SOLE_CORNERS = torch.tensor([_SOLE_LEFT, [[x, -y, z] for x, y, z in _SOLE_LEFT]])


def _foot_up_error(robot, sim, foot_ids: list[int], heading_quat: torch.Tensor) -> torch.Tensor:
    """(2 feet, 2): each sole's up axis in the heading frame's x/y -- zero when the foot is flat."""
    sim.physics_sim_view.update_articulations_kinematic()
    robot.update(0.0)
    up = quat_apply(robot.data.body_quat_w[0, foot_ids], torch.tensor([[0.0, 0.0, 1.0]], device=sim.device).expand(2, 3))
    local = quat_apply(quat_conjugate(heading_quat).expand(2, 4), up)
    return local[:, :2]


def append_settle_transition(
    motion: "InterMimicMotionLoader", robot, robot_joint_indexes: list[int], sim, scene, foot_ids: list[int]
) -> int:
    """Extend the motion with a hold-the-object settle into a stable stance (``--end_mode settle``); returns its
    first frame.

    Arms and head are frozen at the clip's last pose, and the object is carried rigidly with the trunk (applied in
    the bake loop), so the grasp is unchanged. The legs go, by cubic Hermite from the clip's final joint state to
    rest, into: hip yaw and roll 0, knee ``--settle_knee``, hip pitch ``-(knee / 2 + lean)``, and ankle pitch/roll
    solved (Newton, finite differences on FK) so each sole is flat. The root slerps to the heading of the foot that
    is in stance on the clip's last frame (``--settle_heading foot``) or keeps the clip's last trunk heading (``trunk``,
    the default; the stance foot then pivots in place), pitched ``--settle_lean_deg`` forward; the bake loop pins that foot
    where it was, so the other foot is the one that moves and lands beside it. Hand contact stays as on the last
    frame; stance is the last frame's until the final 30% of the transition, then both feet.
    """
    fps = motion.output_fps
    n = motion.output_frames
    steps = max(int(round(args_cli.stand_s * fps)), 1)
    duration = steps / fps
    dev = motion.motion_dof_poss.device
    names = [aliases[0] for aliases in K1_DOF_ALIASES]
    q0, v0 = motion.motion_dof_poss[-1].clone(), motion.motion_dof_vels[-1].clone()

    # Pinned foot: the one in stance on the last frame (the other is mid-step), or none if both / neither.
    pin = None
    if motion.motion_stance is not None:
        last = motion.motion_stance[-1] > 0.5
        if bool(last[0]) != bool(last[1]):
            pin = 0 if bool(last[0]) else 1

    # FK of the last frame: the pinned foot's heading sets the final trunk heading.
    root_states = robot.data.default_root_state.clone()
    root_states[:, :3] = motion.motion_base_poss[-1]
    root_states[:, :2] += scene.env_origins[:, :2]
    root_states[:, 3:7] = motion.motion_base_rots[-1]
    root_states[:, 7:] = 0.0
    robot.write_root_state_to_sim(root_states)
    joint_pos = robot.data.default_joint_pos.clone()
    joint_pos[:, robot_joint_indexes] = q0
    robot.write_joint_state_to_sim(joint_pos, torch.zeros_like(joint_pos))
    sim.physics_sim_view.update_articulations_kinematic()
    robot.update(0.0)

    def yaw_of(q: torch.Tensor) -> float:
        w, x, y, z = q.tolist()
        return math.atan2(2 * (w * z + x * y), 1 - 2 * (y * y + z * z))

    if args_cli.settle_heading == "foot" and pin is not None:
        yaw = yaw_of(robot.data.body_quat_w[0, foot_ids[pin]])
    else:
        yaw = yaw_of(motion.motion_base_rots[-1])
    lean = math.radians(args_cli.settle_lean_deg)
    heading = torch.tensor([math.cos(yaw / 2), 0.0, 0.0, math.sin(yaw / 2)], device=dev)
    pitch = torch.tensor([math.cos(lean / 2), 0.0, math.sin(lean / 2), 0.0], device=dev)  # +y: nose down
    rot1 = quat_mul(heading[None], pitch[None])[0]

    # Target leg pose; ankles then solved for flat soles with the root at its target orientation.
    k = args_cli.settle_knee
    q1 = q0.clone()
    for f_idx, side in enumerate(("Left", "Right")):
        if not (args_cli.settle_stance_leg == "keep" and pin == f_idx):
            q1[names.index(f"{side}_Hip_Yaw")] = 0.0
            q1[names.index(f"{side}_Hip_Roll")] = 0.0
        q1[names.index(f"{side}_Knee_Pitch")] = k
        q1[names.index(f"{side}_Hip_Pitch")] = -(k / 2 + lean)
        q1[names.index(f"{side}_Ankle_Pitch")] = -k / 2
        q1[names.index(f"{side}_Ankle_Roll")] = 0.0
    ankle = [[names.index(f"{side}_Ankle_Pitch"), names.index(f"{side}_Ankle_Roll")] for side in ("Left", "Right")]
    root_states[:, 3:7] = rot1
    robot.write_root_state_to_sim(root_states)

    def err_at(q: torch.Tensor) -> torch.Tensor:
        jp = robot.data.default_joint_pos.clone()
        jp[:, robot_joint_indexes] = q
        robot.write_joint_state_to_sim(jp, torch.zeros_like(jp))
        return _foot_up_error(robot, sim, foot_ids, heading)

    for _ in range(8):
        e = err_at(q1)
        if e.abs().max() < 1e-4:
            break
        for f in range(2):
            jac = torch.zeros(2, 2, device=dev)
            for c in range(2):
                dq = q1.clone()
                dq[ankle[f][c]] += 1e-3
                jac[:, c] = (err_at(dq)[f] - e[f]) / 1e-3
            q1[ankle[f]] -= torch.linalg.solve(jac, e[f])
    tilt = torch.rad2deg(torch.asin(err_at(q1).norm(dim=-1).clamp(max=1.0)))
    print(f"[SETTLE]: target ankles L pitch/roll {q1[ankle[0]].tolist()} R {q1[ankle[1]].tolist()}; "
          f"residual sole tilt {tilt.tolist()} deg", flush=True)

    # Legs: Hermite (q0, v0) -> (q1, 0). Arms and head: frozen at q0, at rest.
    legs = torch.tensor([i for i, nm in enumerate(names) if "Hip" in nm or "Knee" in nm or "Ankle" in nm], device=dev)
    u = (torch.arange(1, steps + 1, device=dev, dtype=torch.float32) / steps).unsqueeze(-1)
    h00, h10, h01 = 2 * u**3 - 3 * u**2 + 1, u**3 - 2 * u**2 + u, -2 * u**3 + 3 * u**2
    d00, d10, d01 = 6 * u**2 - 6 * u, 3 * u**2 - 4 * u + 1, -6 * u**2 + 6 * u
    dof_pos = q0.expand(steps, -1).clone()
    dof_vel = torch.zeros(steps, len(names), device=dev)
    dof_pos[:, legs] = (h00 * q0 + h10 * duration * v0 + h01 * q1)[:, legs]
    dof_vel[:, legs] = ((d00 * q0 + d10 * duration * v0 + d01 * q1) / duration)[:, legs]

    rot0 = motion.motion_base_rots[-1]
    if torch.dot(rot0, rot1) < 0:
        rot1 = -rot1
    sm = 3 * u**2 - 2 * u**3
    angle = torch.acos(torch.clamp(torch.dot(rot0, rot1), -1.0, 1.0))
    if angle < 1e-6:
        rots = rot0.expand(steps, 4).clone()
    else:
        rots = (torch.sin((1 - sm) * angle) * rot0 + torch.sin(sm * angle) * rot1) / torch.sin(angle)

    # Keep the soles from tipping mid-transition: joint-space interpolation alone rolls them onto their toes while
    # the trunk turns and leans. Per frame, solve the ankles so each sole's up axis follows a smoothstep blend from
    # its clip-end tilt to vertical (world frame).
    root_states[:, 3:7] = rot0
    robot.write_root_state_to_sim(root_states)
    jp = robot.data.default_joint_pos.clone()
    jp[:, robot_joint_indexes] = q0
    robot.write_joint_state_to_sim(jp, torch.zeros_like(jp))
    world = torch.tensor([1.0, 0.0, 0.0, 0.0], device=dev)
    sole = SETTLE_SOLE_CORNERS.to(dev)
    up_start = _foot_up_error(robot, sim, foot_ids, world)  # (2, 2): x/y of each sole's up axis at the clip end
    clear_start = None
    clearance_at_start = 0.0
    if pin is not None:
        pts0 = robot.data.body_pos_w[0, foot_ids][:, None, :] + quat_apply(
            robot.data.body_quat_w[0, foot_ids][:, None, :].expand(2, 4, 4), sole
        )
        clearance_at_start = pts0[1 - pin, :, 2].min() - pts0[pin, :, 2].min()
    for f in range(steps):
        root_states[:, 3:7] = rots[f]
        robot.write_root_state_to_sim(root_states)
        target = (1.0 - sm[f]) * up_start
        q = dof_pos[f].clone()

        def err_q(qq: torch.Tensor) -> torch.Tensor:
            jq = robot.data.default_joint_pos.clone()
            jq[:, robot_joint_indexes] = qq
            robot.write_joint_state_to_sim(jq, torch.zeros_like(jq))
            return _foot_up_error(robot, sim, foot_ids, world) - target

        for _ in range(4):
            e = err_q(q)
            if e.abs().max() < 1e-4:
                break
            for side in range(2):
                jac = torch.zeros(2, 2, device=dev)
                for c in range(2):
                    dq = q.clone()
                    dq[ankle[side][c]] += 1e-3
                    jac[:, c] = (err_q(dq)[side] - e[side]) / 1e-3
                q[ankle[side]] -= torch.linalg.solve(jac, e[side])
        # Swing-foot clearance: the bake loop keeps the pinned foot's lowest sole corner on the floor, so the
        # other foot's lowest corner relative to it is its height above the floor. Where that is negative, shorten
        # the swing leg -- more knee, half as much more hip flexion (keeps the foot under the hip) and half as much
        # ankle the other way (hip + knee + ankle pitch unchanged, so the sole keeps its tilt; with the ankle fixed
        # the knee bend tips the toe down and digs it further in) -- then re-solve its ankle, until it clears.
        if pin is not None:
            swing = 1 - pin
            knee_i, hip_i = names.index(f"{('Left', 'Right')[swing]}_Knee_Pitch"), names.index(f"{('Left', 'Right')[swing]}_Hip_Pitch")

            def clearance(qq: torch.Tensor) -> torch.Tensor:
                jq = robot.data.default_joint_pos.clone()
                jq[:, robot_joint_indexes] = qq
                robot.write_joint_state_to_sim(jq, torch.zeros_like(jq))
                sim.physics_sim_view.update_articulations_kinematic()
                robot.update(0.0)
                pts = robot.data.body_pos_w[0, foot_ids][:, None, :] + quat_apply(
                    robot.data.body_quat_w[0, foot_ids][:, None, :].expand(2, 4, 4), sole
                )
                return pts[swing, :, 2].min() - pts[pin, :, 2].min()

            def shortened(delta: float) -> torch.Tensor:
                qq = q.clone()
                qq[knee_i] += delta
                qq[hip_i] -= delta / 2
                qq[ankle[swing][0]] -= delta / 2
                for _ in range(3):
                    e = err_q(qq)
                    jac = torch.zeros(2, 2, device=dev)
                    for c in range(2):
                        dq = qq.clone()
                        dq[ankle[swing][c]] += 1e-3
                        jac[:, c] = (err_q(dq)[swing] - e[swing]) / 1e-3
                    qq[ankle[swing]] -= torch.linalg.solve(jac, e[swing])
                return qq

            # Smallest shortening that reaches the clearance target: bracket by doubling, then bisect, so the
            # correction varies smoothly frame to frame instead of overshooting the way a linearised step does.
            # The target eases from wherever the clip left the swing foot (its toe can already be a few mm below
            # the stance sole) up to +1 mm over the first 30% of the transition, so frame 0 does not jump.
            if clear_start is None:
                clear_start = float(clearance_at_start)
            ramp = min(1.0, (f + 1) / max(1.0, 0.3 * steps))
            margin = clear_start + (1e-3 - clear_start) * (3 * ramp**2 - 2 * ramp**3) if clear_start < 1e-3 else 1e-3
            if clearance(q) < margin:
                lo, hi = 0.0, 0.02
                while clearance(shortened(hi)) < margin and hi < 1.0:
                    lo, hi = hi, hi * 2
                for _ in range(14):
                    mid = 0.5 * (lo + hi)
                    if clearance(shortened(mid)) < margin:
                        lo = mid
                    else:
                        hi = mid
                q = shortened(hi)
        dof_pos[f] = q
    # Velocities of the solved leg joints from the final positions, starting from the clip's last frame.
    seq = torch.cat([q0[None], dof_pos], dim=0)[:, legs]
    dof_vel[:, legs] = (seq[1:] - seq[:-1]) * fps

    def extend(name: str, tail: torch.Tensor):
        setattr(motion, name, torch.cat([getattr(motion, name), tail.to(getattr(motion, name).dtype)], dim=0))

    extend("motion_dof_poss", dof_pos)
    extend("motion_dof_vels", dof_vel)
    extend("motion_base_rots", rots)
    extend("motion_base_poss", motion.motion_base_poss[-1:].expand(steps, 3))
    extend("motion_base_lin_vels", torch.zeros(steps, 3, device=dev))
    extend("motion_base_ang_vels", torch.zeros(steps, 3, device=dev))
    # Object placeholders: the bake loop overwrites them with the trunk-carried pose.
    extend("motion_object_poss", motion.motion_object_poss[-1:].expand(steps, 3))
    extend("motion_object_rots", motion.motion_object_rots[-1:].expand(steps, 4))
    extend("motion_object_lin_vels", torch.zeros(steps, 3, device=dev))
    extend("motion_object_ang_vels", torch.zeros(steps, 3, device=dev))
    extend("motion_contacts", motion.motion_contacts[-1:].expand(steps, -1))
    if motion.motion_stance is not None:
        tail = motion.motion_stance[-1:].expand(steps, -1).clone()
        tail[int(0.7 * steps):] = 1.0
        extend("motion_stance", tail)
    motion.output_frames = n + steps
    motion.settle_pin = pin
    print(
        f"[SETTLE]: appended {steps} frames ({duration:.2f} s): holding the object, knee {k:.2f} rad, lean"
        f" {args_cli.settle_lean_deg:.1f} deg, heading {math.degrees(yaw):.1f} deg, pinned foot"
        f" {['left', 'right'][pin] if pin is not None else 'none (midpoint)'}",
        flush=True,
    )
    return n


def setup_object_physics(obj: RigidObject, scene: InteractiveScene, motion: "InterMimicMotionLoader"):
    """Mass, collider offsets, frame-0 pose and table slab for a physically simulated object."""
    import trimesh

    view = obj.root_physx_view
    ids = torch.arange(view.count, device="cpu")
    mass0 = view.get_masses().clone()
    view.set_masses(torch.full_like(mass0, args_cli.object_mass), ids)
    view.set_inertias(view.get_inertias() * (args_cli.object_mass / mass0.view(-1, 1)), ids)
    view.set_contact_offsets(torch.full_like(view.get_contact_offsets(), 0.02), ids)
    view.set_rest_offsets(torch.full_like(view.get_rest_offsets(), 0.001), ids)

    pos0, quat0 = motion.motion_object_poss[0], motion.motion_object_rots[0]
    state = obj.data.default_root_state.clone()
    state[:, :3] = pos0
    state[:, :2] += scene.env_origins[:, :2]
    state[:, 3:7] = quat0
    state[:, 7:] = 0.0
    obj.write_root_state_to_sim(state)

    w, x, y, z = quat0.cpu().numpy()
    rot = np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])  # fmt: skip
    vertices = np.asarray(trimesh.load(OBJECT_MESH, force="mesh").vertices)
    bottom = float((vertices @ rot.T)[:, 2].min() + pos0[2].item())
    support = scene["support"]
    slab = support.data.default_root_state.clone()
    slab[:, 3:7] = torch.tensor([1.0, 0.0, 0.0, 0.0], device=slab.device)
    if bottom > SUPPORT_MIN_HEIGHT:
        slab[:, :3] = torch.tensor([pos0[0].item(), pos0[1].item(), bottom - 0.5 * SUPPORT_SIZE[2]], device=slab.device)
        slab[:, :2] += scene.env_origins[:, :2]
    else:
        slab[:, :3] = torch.tensor([0.0, 0.0, -10.0], device=slab.device)
    support.write_root_state_to_sim(slab)
    print(
        f"[PHYSICS]: object {args_cli.object_mass} kg, bottom {bottom:+.3f} m ->"
        f" {'table slab' if bottom > SUPPORT_MIN_HEIGHT else 'floor'}; robot kinematic, object simulated",
        flush=True,
    )


def _quat_apply_np(quat: np.ndarray, vec: np.ndarray) -> np.ndarray:
    """Rotate vectors (..., 3) by wxyz quaternions (..., 4)."""
    w, xyz = quat[..., :1], quat[..., 1:]
    t = 2.0 * np.cross(xyz, vec)
    return vec + w * t + np.cross(xyz, t)


def cli_palm_offset() -> float | np.ndarray:
    """``--palm_offset`` as either a scalar (y-only) or the left hand's (3,) offset vector."""
    values = args_cli.palm_offset
    if len(values) == 1:
        return float(values[0])
    if len(values) == 3:
        return np.asarray(values, dtype=float)
    raise SystemExit(f"--palm_offset takes 1 or 3 values, got {len(values)}")


def palm_offset_vectors(offset) -> np.ndarray:
    """(2, 3) per-hand keypoint offsets.

    A scalar is the y-only convention. A (3,) vector is the left hand's offset and the right hand mirrors it in
    y. A (2, 3) array is used as given, which is how the per-hand fitted offsets are checked.
    """
    array = np.asarray(offset, dtype=float)
    if array.ndim == 0:
        return np.array([[0.0, sign * float(array), 0.0] for sign in PALM_SIGNS])
    if array.shape == (3,):
        return np.stack([array, array * np.array([1.0, -1.0, 1.0])])
    return array.reshape(2, 3)


def palm_positions_np(log: dict, robot, offset: float | np.ndarray) -> np.ndarray:
    """World palm keypoints (T, 2, 3) from the logged link poses and the per-hand local offsets."""
    ids = [robot.body_names.index(name) for name in PALM_BODY_NAMES]
    pos, quat = log["body_pos_w"][:, ids], log["body_quat_w"][:, ids]
    local = palm_offset_vectors(offset).astype(pos.dtype)
    return pos + _quat_apply_np(quat, np.broadcast_to(local, pos.shape))


def palm_to_object_distance(log: dict, robot, offset: float | np.ndarray, mesh, frames: np.ndarray, side: int) -> np.ndarray:
    """Distance from the palm keypoint to the object surface, on the given frames of one hand."""
    import trimesh

    palm = palm_positions_np(log, robot, offset)[frames, side]
    obj_pos, obj_quat = log["object_pos_w"][frames], log["object_quat_w"][frames]
    conj = obj_quat * np.array([1.0, -1.0, -1.0, -1.0], dtype=obj_quat.dtype)
    local = _quat_apply_np(conj, palm - obj_pos)  # into the object frame, where the mesh lives
    return trimesh.proximity.closest_point(mesh, local)[1]


def contact_points_object_frame(log: dict, robot, offset, frames: np.ndarray, side: int) -> np.ndarray:
    """Palm keypoint expressed in the object's own frame, on the given frames of one hand: (F, 3).

    This is exactly the quantity the HOI observation is built from -- no projection onto the mesh. Its spread
    over the contact window says whether the capture holds the object at a repeatable place on the palm.
    """
    palm = palm_positions_np(log, robot, offset)[frames, side]
    obj_pos, obj_quat = log["object_pos_w"][frames], log["object_quat_w"][frames]
    flip = np.array([1.0, -1.0, -1.0, -1.0], dtype=obj_quat.dtype)
    return _quat_apply_np(obj_quat * flip, palm - obj_pos)


def report_contact_points(log: dict, robot):
    """Check the palm keypoints against the object over the reference's labelled contact frames.

    The contact point the HOI observations are built from is the palm position expressed in the object frame, so
    it is only meaningful if the palm keypoint actually lands on the object when the capture says it should.
    This prints that distance, and scans --palm_offset to show which offset the capture itself implies.
    """
    import trimesh

    contact = log["contact"] > 0.5
    print("[CONTACT]: ---- palm keypoints vs object ----")
    if not contact.any():
        print("[CONTACT]: the clip labels no contact frames; nothing to check.")
        return
    if not os.path.isfile(OBJECT_MESH):
        print(f"[CONTACT]: no mesh at {OBJECT_MESH}; skipping the surface check.")
        return
    mesh = trimesh.load(OBJECT_MESH, force="mesh")
    print(f"[CONTACT]: mesh {os.path.basename(OBJECT_MESH)}, watertight={mesh.is_watertight}, extents="
          f"{np.round(mesh.extents, 3).tolist()} m")

    for side, name in enumerate(PALM_BODY_NAMES):
        frames = np.flatnonzero(contact[:, side])
        if frames.size == 0:
            print(f"[CONTACT]: {name}: no labelled contact frames")
            continue
        sampled = frames[:: max(1, frames.size // 200)]  # bound the proximity queries
        gap = palm_to_object_distance(log, robot, cli_palm_offset(), mesh, sampled, side)
        point = contact_points_object_frame(log, robot, cli_palm_offset(), sampled, side)
        print(
            f"[CONTACT]: {name}: {frames.size} contact frames ({frames.size / len(contact) * 100:.0f}% of clip)\n"
            f"[CONTACT]:   contact point in object frame: {np.round(point.mean(axis=0), 3).tolist()} m"
            f"  +/- {np.round(point.std(axis=0), 3).tolist()}\n"
            f"[CONTACT]:   drift over the window        : {np.round(point.max(axis=0) - point.min(axis=0), 3).tolist()} m\n"
            f"[CONTACT]:   palm to object surface       : mean {gap.mean() * 100:.1f} cm,"
            f" min {gap.min() * 100:.1f}, max {gap.max() * 100:.1f}"
        )
    print("[CONTACT]: the contact point is the palm keypoint in the object frame as-is -- it is not projected onto"
          " the mesh, so a few cm of surface gap is expected and fine. What matters is the spread: a tight one"
          " means the capture holds the object at a repeatable place, which is what makes the point learnable.")


def report_bake_quality(log: dict, motion: InterMimicMotionLoader, robot):
    """Cross-checks the regenerated bodies against the source file."""
    root_body_index = 0
    # Only the source frames round-trip; --start_s / --stand_s transitions around them are synthesized.
    n_src = motion.source_body_lin_vels.shape[0]
    lead = getattr(motion, "lead_frames", 0)
    clip = slice(lead, lead + n_src)
    src_root_pos = motion.motion_base_poss[clip].cpu().numpy()
    baked_root_pos = log["body_pos_w"][clip, root_body_index]
    pos_err = np.abs(baked_root_pos - src_root_pos).max()

    src_root_vel = motion.source_body_lin_vels[:, root_body_index].cpu().numpy()
    baked_root_vel = log["body_lin_vel_w"][clip, root_body_index]
    vel_err = np.abs(baked_root_vel - src_root_vel).max()

    min_z = log["body_pos_w"][..., 2].min()
    min_z_body = robot.body_names[int(np.argmin(log["body_pos_w"][..., 2].min(axis=0)))]

    obj_min_z = log["object_pos_w"][..., 2].min()
    obj_max_z = log["object_pos_w"][..., 2].max()

    print("[CHECK]: ---- bake quality ----")
    feet = [robot.body_names.index(name) for name in ("left_foot_link", "right_foot_link")]
    if lead:
        head = log["body_pos_w"][: lead + 1, feet]  # lead-in + the clip's first frame
        slide = np.linalg.norm(head[:, :, :2] - head[-1:, :, :2], axis=-1).max(axis=0)
        rise = (head[:, :, 2] - head[-1:, :, 2]).max(axis=0)
        jv = log["joint_vel"][lead - 1 : lead + 1]
        print(f"[CHECK]: lead-in frames                  : {lead}")
        print(f"[CHECK]: lead foot slide L/R (max, xy)   : {slide[0]:.3f} / {slide[1]:.3f} m")
        print(f"[CHECK]: lead foot rise L/R (max, z)     : {rise[0]:.3f} / {rise[1]:.3f} m")
        print(f"[CHECK]: lead root height start          : {log['body_pos_w'][0, 0, 2]:.3f} m (clip start {log['body_pos_w'][lead, 0, 2]:.3f})")
        print(f"[CHECK]: joint vel step at lead->clip    : {np.abs(jv[1] - jv[0]).max():.3f} rad/s")
    if log["body_pos_w"].shape[0] > lead + n_src:
        stand0 = lead + n_src  # index of the first stand-transition frame
        tail = log["body_pos_w"][stand0 - 1 :, feet]  # last clip frame + transition
        slide = np.linalg.norm(tail[:, :, :2] - tail[:1, :, :2], axis=-1).max(axis=0)
        lift = (tail[:, :, 2] - tail[:1, :, 2]).max(axis=0)
        jv = log["joint_vel"][stand0 - 1 : stand0 + 1]
        print(f"[CHECK]: stand transition frames         : {log['body_pos_w'].shape[0] - stand0}")
        print(f"[CHECK]: stand foot slide L/R (max, xy)  : {slide[0]:.3f} / {slide[1]:.3f} m")
        print(f"[CHECK]: stand foot rise L/R (max, z)    : {lift[0]:.3f} / {lift[1]:.3f} m")
        print(f"[CHECK]: stand root height end           : {log['body_pos_w'][-1, 0, 2]:.3f} m (clip end {log['body_pos_w'][stand0 - 1, 0, 2]:.3f})")
        print(f"[CHECK]: joint vel step at clip->stand   : {np.abs(jv[1] - jv[0]).max():.3f} rad/s")
    print(f"[CHECK]: frames baked                    : {log['body_pos_w'].shape[0]}")
    print(f"[CHECK]: root pos round-trip (max abs)   : {pos_err:.6f} m   (expect ~0)")
    print(f"[CHECK]: root lin vel round-trip (max abs): {vel_err:.6f} m/s (expect ~0)")
    print(f"[CHECK]: lowest body over the motion     : {min_z:.4f} m on '{min_z_body}'")
    print(f"[CHECK]: object height range              : [{obj_min_z:.4f}, {obj_max_z:.4f}] m")
    if pos_err > 1e-3:
        print("[CHECK]: WARNING root position did not round-trip; the source root frame likely differs from Trunk.")
    if vel_err > 1e-2:
        print("[CHECK]: WARNING root velocity did not round-trip; check the source velocity reference point.")
    if min_z < -0.02:
        print("[CHECK]: WARNING bodies penetrate the ground plane; the motion may need a z offset.")
    if obj_min_z < -0.02:
        print("[CHECK]: WARNING object penetrates the ground plane; check the object frame convention.")


def main():
    """Main function."""
    # Load kit helper
    sim_cfg = sim_utils.SimulationCfg(device=args_cli.device)
    sim_cfg.dt = 1.0 / args_cli.output_fps
    if args_cli.object_physics:
        sim_cfg.dt /= args_cli.substeps  # 0.005 s at 50 fps, as in training
    sim = SimulationContext(sim_cfg)
    # Design scene
    scene_cfg = ReplayMotionsSceneCfg(num_envs=1, env_spacing=2.0)
    if args_cli.object_physics:
        scene_cfg.support = RigidObjectCfg(
            prim_path="{ENV_REGEX_NS}/Support",
            spawn=sim_utils.CuboidCfg(
                size=SUPPORT_SIZE,
                rigid_props=sim_utils.RigidBodyPropertiesCfg(kinematic_enabled=True),
                collision_props=sim_utils.CollisionPropertiesCfg(),
                visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.35, 0.3, 0.25)),
            ),
            init_state=RigidObjectCfg.InitialStateCfg(pos=(0.0, 0.0, -10.0)),
        )
    if args_cli.video is not None:
        scene_cfg.camera = CameraCfg(
            prim_path="{ENV_REGEX_NS}/RenderCamera",
            update_period=0.0,
            height=args_cli.video_height,
            width=args_cli.video_width,
            data_types=["rgb"],
            spawn=sim_utils.PinholeCameraCfg(
                focal_length=args_cli.camera_focal,
                focus_distance=400.0,
                horizontal_aperture=20.955,
                clipping_range=(0.1, 1.0e5),
            ),
        )
    scene = InteractiveScene(scene_cfg)
    if args_cli.object_physics and not args_cli.support_collides_robot:
        # Table only touches the object: filter every robot link against it (must be authored before sim.reset()).
        from pxr import Usd, UsdPhysics

        stage = sim.stage
        for env_ns in scene.env_prim_paths:
            rel = UsdPhysics.FilteredPairsAPI.Apply(stage.GetPrimAtPath(f"{env_ns}/Support")).CreateFilteredPairsRel()
            links = [
                prim.GetPath()
                for prim in Usd.PrimRange(stage.GetPrimAtPath(f"{env_ns}/Robot"))
                if prim.HasAPI(UsdPhysics.RigidBodyAPI)
            ]
            for link in links:
                rel.AddTarget(link)
        print(f"[PHYSICS]: table collision filtered against {len(links)} robot links", flush=True)
    # Play the simulator
    sim.reset()
    # Now we are ready!
    print("[INFO]: Setup complete...")
    # Run the simulator
    run_simulator(sim, scene)


if __name__ == "__main__":
    # Run the one-shot bake/render job. All user outputs (NPZ + MP4) are fully
    # flushed before main() returns.
    main()

    # In headless camera workflows, Isaac Sim can hang during its default
    # graceful shutdown while waiting on Replicator/Kit cleanup. This script is
    # a one-shot renderer, so there is nothing left to preserve after main().
    # Skip those shutdown waits and terminate Kit immediately.
    print("[INFO]: Closing Isaac Sim...", flush=True)
    simulation_app.close(wait_for_replicator=False, skip_cleanup=True)
