"""This script replays an InterMimic motion tensor and outputs it to a npz file.

The InterMimic file is a bare ``torch.float32`` tensor of shape ``(T, raw)`` sampled at a
fixed fps, with the layout built by ``_make_obs_layout(num_bodies, num_dof)``::

    root_pos      [0:3]                       world frame, m
    root_rot      [3:7]                       quaternion, xyzw
    root_lin_vel  [7:10]                      world frame, m/s
    root_ang_vel  [10:13]                     world frame, rad/s
    dof_pos       [13 : 13+ND]                rad
    dof_vel       [13+ND : 13+2*ND]           rad/s
    obj_pos       [13+2*ND : 16+2*ND]         world frame, m
    obj_rot       [16+2*ND : 20+2*ND]         quaternion, xyzw
    obj_lin_vel   [20+2*ND : 23+2*ND]         world frame, m/s
    obj_ang_vel   [23+2*ND : 26+2*ND]         world frame, rad/s
    body_*        [26+2*ND : 26+2*ND+13*NB]   ignored, regenerated from the Booster model
    contact       trailing NB                 per-body 0/1; CONTACT_CHANNELS carried through

The object block is carried straight through to the output npz (as ``object_pos_w``,
``object_quat_w``, ``object_lin_vel_w``, ``object_ang_vel_w``): unlike the robot body block,
there is no differing source/target body set to reconcile, so no re-simulation is needed.

Reference points match Isaac Lab throughout: positions and orientations are link frame,
linear velocities are center of mass, and angular velocity is frame-independent. That is
exactly how ``write_root_state_to_sim`` reads a root state, so the root block transfers
with no conversion beyond the quaternion layout.

Unlike :file:`csv_to_npz.py`, joint and root velocities are taken straight from the file
rather than finite-differenced from the positions, so fast parts of the motion keep their
true derivatives. The body blocks are still discarded and regenerated by driving the
Booster articulation, because the source model exposes a different body set, ordering and
link geometry than the Booster K1 model the policy is trained against.

.. code-block:: bash

    # Bake only
    python pt_to_npz.py --headless \
        --input_file ./booster_assets/motions/K1/sub4_smallbox_047_smallbox_intermimic_original.pt \
        --output_name ./booster_assets/motions/K1/sub4_smallbox_047.npz

    # Bake + offline/headless MP4 render
    python pt_to_npz.py --headless \
        --input_file ./booster_assets/motions/K1/sub4_smallbox_047_smallbox_intermimic_original.pt \
        --output_name ./booster_assets/motions/K1/sub4_smallbox_047.npz \
        --video ./sub4_smallbox_047.mp4
"""

"""Launch Isaac Sim Simulator first."""

import argparse
import sys
from pathlib import Path
import numpy as np

from isaaclab.app import AppLauncher

# add argparse arguments
parser = argparse.ArgumentParser(description="Replay an InterMimic motion tensor and output to a npz file.")
parser.add_argument("--input_file", type=str, required=True, help="The path to the input InterMimic .pt file.")
parser.add_argument("--input_fps", type=int, default=50, help="The fps of the input motion.")
parser.add_argument(
    "--frame_range",
    nargs=2,
    type=int,
    metavar=("START", "END"),
    help=(
        "frame range: START END (both inclusive). The frame index starts from 1. If not provided, all frames will be"
        " loaded."
    ),
)
parser.add_argument("--output_name", type=str, required=True, help="The name of the motion npz file.")
parser.add_argument("--output_fps", type=int, default=50, help="The fps of the output motion. Must equal --input_fps.")
parser.add_argument("--num_dof", type=int, default=22, help="Number of actuated DOF in the source file (K1: 22).")
parser.add_argument(
    "--object",
    type=str,
    default="smallbox_0539923",
    choices=("smallbox_0539923", "largebox_0539923"),
    help="Which captured object the motion interacts with; must match the source capture.",
)
parser.add_argument("--video", type=str, default=None, help="Optional output MP4 path for offline rendering.")
parser.add_argument("--video_width", type=int, default=1280, help="Rendered video width.")
parser.add_argument("--video_height", type=int, default=720, help="Rendered video height.")
parser.add_argument(
    "--camera_offset",
    type=float,
    nargs=3,
    default=(1.8, 1.8, 0.6),
    metavar=("X", "Y", "Z"),
    help="Camera position offset in world axes relative to the look-at point.",
)
parser.add_argument(
    "--camera_view",
    choices=["world", "front"],
    default="world",
    help=(
        "'world': --camera_offset is in world axes. 'front': --camera_offset is in the robot's heading frame at"
        " frame 0 (x forward, y left), and defaults to (2.2, 0, 0.6), i.e. looking at the robot's face."
    ),
)
parser.add_argument(
    "--camera_focal",
    type=float,
    default=18.0,
    help=(
        "Focal length in mm against a 20.955 mm aperture. 24 mm gives a 28 deg vertical field of view, which"
        " crops a 1.2 m robot at this distance; 18 mm gives 36 deg."
    ),
)
parser.add_argument(
    "--camera_lookat_offset",
    type=float,
    nargs=3,
    default=(0.0, 0.0, -0.05),
    metavar=("X", "Y", "Z"),
    help=(
        "Camera look-at offset in world axes. X/Y track the robot root; Z is measured from the standing root"
        " height of the first frame, so the frame does not dive when the robot squats."
    ),
)
parser.add_argument(
    "--object_physics",
    action="store_true",
    help=(
        "Simulate the object instead of replaying it: it is placed at its frame-0 pose (on a table slab if it"
        " starts off the ground) and then only reacts to contact with the kinematically replayed robot. The npz"
        " then records the simulated object, so write it somewhere other than the training motions."
    ),
)
parser.add_argument("--object_mass", type=float, default=0.5, help="Object mass with --object_physics, kg.")
parser.add_argument(
    "--robot_drive",
    choices=["teleport", "pd"],
    default="teleport",
    help=(
        "With --object_physics: 'teleport' writes the joint angles every substep (the hands are moved into the"
        " object, not swept, so PhysX only depenetrates it slowly); 'pd' pins the root to the reference but drives"
        " the joints through the K1 actuators toward the reference, so the arms are real colliding bodies."
    ),
)
parser.add_argument(
    "--support_size", type=float, nargs=3, default=(0.6, 0.6, 0.04), metavar=("X", "Y", "Z"),
    help="Table top size with --object_physics, m. Its top face sits at the object's frame-0 bottom.",
)
parser.add_argument(
    "--support_collides_robot", action="store_true",
    help="Let the robot collide with the table (default: filtered out, so a wide table cannot catch the legs).",
)
parser.add_argument("--substeps", type=int, default=4, help="Physics substeps per frame with --object_physics.")

# append AppLauncher cli args
AppLauncher.add_app_launcher_args(parser)
# parse the arguments
args_cli = parser.parse_args()

# Camera sensors require rendering extensions even when running headless.
# Turn them on automatically only when MP4 output was requested.
if args_cli.video is not None:
    args_cli.enable_cameras = True

# launch omniverse app
app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

"""Rest everything follows."""

import torch

import isaaclab.sim as sim_utils
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObject, RigidObjectCfg
from isaaclab.scene import InteractiveScene, InteractiveSceneCfg
from isaaclab.sensors import Camera, CameraCfg
from isaaclab.sim import SimulationContext
from isaaclab.utils import configclass
from isaaclab.utils.assets import ISAAC_NUCLEUS_DIR

##
# Pre-defined configs
##
from booster_train.assets.robots.booster import BOOSTER_K1_CFG as ROBOT_CFG
from booster_assets import BOOSTER_ASSETS_DIR
from booster_train.assets.objects.boxes import LARGEBOX_0539923_CFG, SMALLBOX_0539923_CFG

# The object is only replayed kinematically here, but it has to be the right mesh: the npz carries the object
# pose straight through, and the rendered video is what tells you the capture and the asset agree.
OBJECT_CFGS = {"smallbox_0539923": SMALLBOX_0539923_CFG, "largebox_0539923": LARGEBOX_0539923_CFG}
OBJECT_CFG = OBJECT_CFGS[args_cli.object]
OBJECT_MESH = f"{BOOSTER_ASSETS_DIR}/motions/K1/{args_cli.object}/{args_cli.object}.obj"
SUPPORT_SIZE = tuple(args_cli.support_size)
SUPPORT_MIN_HEIGHT = 0.05

# The source DOF order, one row per actuated joint, in the order the columns appear in the
# .pt file. Each row lists the aliases this joint is known by, because the InterMimic
# retarget model, the Booster URDF and booster_assets.motions all spell it differently.
# The order below is the joint order of the InterMimic K1 MJCF and is identical to
# booster_assets.motions.K1_JOINT_NAMES.
K1_DOF_ALIASES = [
    ("AAHead_yaw", "aahead_yaw_joint"),
    ("Head_pitch", "aahead_pitch_joint"),
    ("ALeft_Shoulder_Pitch", "aaleft_shoulder_pitch_joint", "left_shoulder_pitch_joint"),
    ("Left_Shoulder_Roll", "left_shoulder_roll_joint"),
    ("Left_Elbow_Pitch", "left_elbow_pitch_joint"),
    ("Left_Elbow_Yaw", "left_elbow_yaw_joint"),
    ("ARight_Shoulder_Pitch", "aaright_shoulder_pitch_joint", "right_shoulder_pitch_joint"),
    ("Right_Shoulder_Roll", "right_shoulder_roll_joint"),
    ("Right_Elbow_Pitch", "right_elbow_pitch_joint"),
    ("Right_Elbow_Yaw", "right_elbow_yaw_joint"),
    ("Left_Hip_Pitch", "left_hip_pitch_joint"),
    ("Left_Hip_Roll", "left_hip_roll_joint"),
    ("Left_Hip_Yaw", "left_hip_yaw_joint"),
    ("Left_Knee_Pitch", "left_knee_pitch_joint"),
    ("Left_Ankle_Pitch", "left_ankle_pitch_joint"),
    ("Left_Ankle_Roll", "left_ankle_roll_joint"),
    ("Right_Hip_Pitch", "right_hip_pitch_joint"),
    ("Right_Hip_Roll", "right_hip_roll_joint"),
    ("Right_Hip_Yaw", "right_hip_yaw_joint"),
    ("Right_Knee_Pitch", "right_knee_pitch_joint"),
    ("Right_Ankle_Pitch", "right_ankle_pitch_joint"),
    ("Right_Ankle_Roll", "right_ankle_roll_joint"),
]

# Bodies the shipped K1 tracking tasks ask for. Only used to warn when the spawned model
# cannot supply them, which means the baked npz will not load in those tasks.
TASK_BODY_NAMES = [
    "Trunk",
    "Head_2",
    "Left_Hip_Roll",
    "Left_Shank",
    "left_foot_link",
    "Right_Hip_Roll",
    "Right_Shank",
    "right_foot_link",
    "Left_Arm_2",
    "Left_Arm_3",
    "left_hand_link",
    "Right_Arm_2",
    "Right_Arm_3",
    "right_hand_link",
]

# Contact channels carried into the npz, as (source contact index, K1 body name).
CONTACT_CHANNELS = [(6, "left_hand_link"), (11, "right_hand_link")]
CONTACT_SOURCE_INDEXES = [index for index, _ in CONTACT_CHANNELS]
CONTACT_NAMES = [name for _, name in CONTACT_CHANNELS]


@configclass
class ReplayMotionsSceneCfg(InteractiveSceneCfg):
    """Configuration for a replay motions scene."""

    # ground plane
    ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())

    # lights
    sky_light = AssetBaseCfg(
        prim_path="/World/skyLight",
        spawn=sim_utils.DomeLightCfg(
            intensity=750.0,
            texture_file=f"{ISAAC_NUCLEUS_DIR}/Materials/Textures/Skies/PolyHaven/kloofendal_43d_clear_puresky_4k.hdr",
        ),
    )

    # articulation
    robot: ArticulationCfg = ROBOT_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")

    # tracked object
    object: RigidObjectCfg = OBJECT_CFG.replace(prim_path="{ENV_REGEX_NS}/Object")

    # Table slab under an object that starts off the ground; only spawned with --object_physics.
    support: RigidObjectCfg | None = None

    # Filled in from main() only when --video is requested, so normal NPZ baking
    # does not pay the camera/rendering cost.
    camera: CameraCfg | None = None


class InterMimicMotionLoader:
    def __init__(
        self,
        motion_file: str,
        input_fps: int,
        output_fps: int,
        num_dof: int,
        device: torch.device,
        frame_range: tuple[int, int] | None,
    ):
        if input_fps != output_fps:
            raise ValueError(
                f"--input_fps ({input_fps}) must equal --output_fps ({output_fps}). Resampling would force the"
                " velocities to be re-derived from interpolated positions, which is the artifact this script exists"
                " to avoid. Resample the source motion instead."
            )
        self.motion_file = motion_file
        self.input_fps = input_fps
        self.output_fps = output_fps
        self.output_dt = 1.0 / self.output_fps
        self.num_dof = num_dof
        self.current_idx = 0
        self.device = device
        self.frame_range = frame_range
        self._load_motion()

    def _load_motion(self):
        """Loads the motion from the InterMimic .pt file."""
        motion = torch.load(self.motion_file, map_location="cpu", weights_only=False)
        if not torch.is_tensor(motion):
            raise TypeError(f"Expected a bare torch.Tensor in {self.motion_file}, got {type(motion)}.")
        if motion.ndim != 2:
            raise ValueError(f"Expected a (T, raw) tensor, got shape {tuple(motion.shape)}.")

        # raw = 26 + 2 * ND + 14 * NB, so NB follows from the tensor width.
        nd = self.num_dof
        residual = motion.shape[1] - 26 - 2 * nd
        if residual <= 0 or residual % 14 != 0:
            raise ValueError(
                f"Tensor width {motion.shape[1]} is not consistent with num_dof={nd}: expected"
                f" 26 + 2*{nd} + 14*NB for an integer NB."
            )
        self.num_bodies = residual // 14

        if self.frame_range is not None:
            motion = motion[self.frame_range[0] - 1 : self.frame_range[1]]
        motion = motion.to(torch.float32).to(self.device)
        self.raw = motion

        self.motion_base_poss = motion[:, 0:3]
        self.motion_base_rots = motion[:, 3:7][:, [3, 0, 1, 2]]  # convert to wxyz
        self.motion_base_lin_vels = motion[:, 7:10]
        self.motion_base_ang_vels = motion[:, 10:13]
        self.motion_dof_poss = motion[:, 13 : 13 + nd]
        self.motion_dof_vels = motion[:, 13 + nd : 13 + 2 * nd]

        obj_start = 13 + 2 * nd
        self.motion_object_poss = motion[:, obj_start : obj_start + 3]
        self.motion_object_rots = motion[:, obj_start + 3 : obj_start + 7][:, [3, 0, 1, 2]]  # convert to wxyz
        self.motion_object_lin_vels = motion[:, obj_start + 7 : obj_start + 10]
        self.motion_object_ang_vels = motion[:, obj_start + 10 : obj_start + 13]

        # Kept only for the post-bake diagnostics; the final reference regenerates these.
        body_start = 26 + 2 * nd
        nb = self.num_bodies
        self.source_body_poss = motion[:, body_start : body_start + nb * 3].view(-1, nb, 3)
        self.source_body_lin_vels = motion[:, body_start + nb * 7 : body_start + nb * 10].view(-1, nb, 3)

        # Per-body contact flags trail the body block. 6 = left_hand_link, 11 = right_hand_link:
        # verified against the object trajectory (on at grasp, off together at set-down).
        self.motion_contacts = motion[:, body_start + 13 * nb : body_start + 14 * nb][:, CONTACT_SOURCE_INDEXES]

        quat_norm = self.motion_base_rots.norm(dim=-1)
        if not torch.allclose(quat_norm, torch.ones_like(quat_norm), atol=1e-3):
            raise ValueError(f"Root quaternions are not unit norm (min {quat_norm.min()}, max {quat_norm.max()}).")

        obj_quat_norm = self.motion_object_rots.norm(dim=-1)
        if not torch.allclose(obj_quat_norm, torch.ones_like(obj_quat_norm), atol=1e-3):
            raise ValueError(
                f"Object quaternions are not unit norm (min {obj_quat_norm.min()}, max {obj_quat_norm.max()})."
            )

        self.output_frames = motion.shape[0]
        self.duration = (self.output_frames - 1) * self.output_dt
        print(
            f"Motion loaded ({self.motion_file}), duration: {self.duration} sec, frames: {self.output_frames},"
            f" bodies: {self.num_bodies}, dof: {nd}"
        )

    def get_next_state(self):
        """Gets the next state of the motion."""
        state = (
            self.motion_base_poss[self.current_idx : self.current_idx + 1],
            self.motion_base_rots[self.current_idx : self.current_idx + 1],
            self.motion_base_lin_vels[self.current_idx : self.current_idx + 1],
            self.motion_base_ang_vels[self.current_idx : self.current_idx + 1],
            self.motion_dof_poss[self.current_idx : self.current_idx + 1],
            self.motion_dof_vels[self.current_idx : self.current_idx + 1],
            self.motion_object_poss[self.current_idx : self.current_idx + 1],
            self.motion_object_rots[self.current_idx : self.current_idx + 1],
            self.motion_object_lin_vels[self.current_idx : self.current_idx + 1],
            self.motion_object_ang_vels[self.current_idx : self.current_idx + 1],
            self.motion_contacts[self.current_idx : self.current_idx + 1],
        )
        self.current_idx += 1
        reset_flag = False
        if self.current_idx >= self.output_frames:
            self.current_idx = 0
            reset_flag = True
        return state, reset_flag


def resolve_joint_indexes(robot_joint_names: list[str], aliases: list[tuple[str, ...]]) -> list[int]:
    """Maps each source DOF column onto an index into the spawned robot's joint order."""
    indexes = []
    unresolved = []
    for row in aliases:
        for name in row:
            if name in robot_joint_names:
                indexes.append(robot_joint_names.index(name))
                break
        else:
            unresolved.append(row)
    if unresolved:
        raise RuntimeError(
            "Could not map every source DOF onto the spawned robot.\n"
            f"  unresolved: {unresolved}\n"
            f"  robot.joint_names: {robot_joint_names}\n"
            "The installed booster_assets K1 model does not match the one this motion was retargeted against."
        )
    if len(set(indexes)) != len(indexes):
        raise RuntimeError(f"Source DOFs mapped onto duplicate robot joints: {indexes}")
    return indexes



class Mp4Writer:
    """Small streaming MP4 writer so we never keep the full video in RAM."""

    def __init__(self, path: str, fps: int):
        try:
            import imageio.v2 as imageio
        except ImportError as exc:
            raise RuntimeError(
                "MP4 output requires imageio and imageio-ffmpeg. Install them with:\n"
                "  pip install imageio imageio-ffmpeg"
            ) from exc

        self.path = path
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        self._writer = imageio.get_writer(
            path,
            fps=fps,
            codec="libx264",
            quality=8,
            macro_block_size=None,
        )

    def append(self, rgb: torch.Tensor):
        """Append one HxWx3/4 torch RGB(A) frame."""
        frame = rgb.detach().cpu().numpy()
        if frame.shape[-1] == 4:
            frame = frame[..., :3]

        # Current Isaac Lab RGB camera output is uint8, but keep this robust to
        # float renderers as well.
        if frame.dtype != np.uint8:
            if np.issubdtype(frame.dtype, np.floating) and frame.max() <= 1.0:
                frame = frame * 255.0
            frame = np.clip(frame, 0, 255).astype(np.uint8)

        self._writer.append_data(frame)

    def close(self):
        if self._writer is not None:
            print(f"[INFO]: Finalizing video: {self.path}...", flush=True)
            self._writer.close()
            self._writer = None
        print(f"[INFO]: Video saved to {self.path}", flush=True)


def run_simulator(sim: sim_utils.SimulationContext, scene: InteractiveScene):
    """Runs the simulation loop."""
    # Load motion
    motion = InterMimicMotionLoader(
        motion_file=args_cli.input_file,
        input_fps=args_cli.input_fps,
        output_fps=args_cli.output_fps,
        num_dof=args_cli.num_dof,
        device=sim.device,
        frame_range=args_cli.frame_range,
    )

    # Extract scene entities
    robot = scene["robot"]
    obj: RigidObject = scene["object"]
    camera: Camera | None = scene["camera"] if args_cli.video is not None else None
    video_writer = Mp4Writer(args_cli.video, args_cli.output_fps) if args_cli.video is not None else None
    camera_anchor_z = None  # standing root height, captured on the first rendered frame
    camera_offset = torch.tensor(args_cli.camera_offset, device=sim.device, dtype=torch.float32).unsqueeze(0)
    camera_lookat_offset = torch.tensor(
        args_cli.camera_lookat_offset, device=sim.device, dtype=torch.float32
    ).unsqueeze(0)

    robot_joint_indexes = resolve_joint_indexes(list(robot.joint_names), K1_DOF_ALIASES)
    if args_cli.object_physics:
        setup_object_physics(obj, scene, motion)
    prev = None  # previous frame's robot state, interpolated across the physics substeps
    if len(robot.joint_names) != len(robot_joint_indexes):
        print(
            f"[WARN]: the robot has {len(robot.joint_names)} joints but the motion only drives"
            f" {len(robot_joint_indexes)}. The rest stay at their default pose."
        )
    missing_bodies = [name for name in TASK_BODY_NAMES if name not in robot.body_names]
    if missing_bodies:
        print(
            f"[WARN]: the spawned model is missing bodies the shipped K1 tasks track: {missing_bodies}.\n"
            f"[WARN]: robot.body_names = {list(robot.body_names)}\n"
            "[WARN]: the npz will still be written, but MotionLoader will raise on these names at train time."
        )

    # ------- data logger -------------------------------------------------------
    log = {
        "fps": [args_cli.output_fps],
        "joint_pos": [],
        "joint_vel": [],
        "body_pos_w": [],
        "body_quat_w": [],
        "body_lin_vel_w": [],
        "body_ang_vel_w": [],
        "object_pos_w": [],
        "object_quat_w": [],
        "object_lin_vel_w": [],
        "object_ang_vel_w": [],
        "contact": [],
        "joint_names": np.array(robot.joint_names),
        "body_names": np.array(robot.body_names),
        "contact_names": np.array(CONTACT_NAMES),
    }
    file_saved = False
    # --------------------------------------------------------------------------

    # Simulation loop
    while simulation_app.is_running():
        (
            (
                motion_base_pos,
                motion_base_rot,
                motion_base_lin_vel,
                motion_base_ang_vel,
                motion_dof_pos,
                motion_dof_vel,
                motion_object_pos,
                motion_object_rot,
                motion_object_lin_vel,
                motion_object_ang_vel,
                motion_contact,
            ),
            reset_flag,
        ) = motion.get_next_state()

        if args_cli.object_physics:
            # Kinematic robot, physical object: sweep the robot from the previous frame's pose to this one across
            # the substeps (re-written every substep so gravity and the PD never act on it), and only step physics.
            cur = (motion_base_pos, motion_base_rot, motion_dof_pos)
            if prev is None:
                prev = cur
            for k in range(1, args_cli.substeps + 1):
                a = k / args_cli.substeps
                q0, q1 = prev[1], cur[1]
                q1 = torch.where((q0 * q1).sum(-1, keepdim=True) < 0, -q1, q1)
                root_states = robot.data.default_root_state.clone()
                root_states[:, :3] = (1 - a) * prev[0] + a * cur[0]
                root_states[:, :2] += scene.env_origins[:, :2]
                root_states[:, 3:7] = torch.nn.functional.normalize((1 - a) * q0 + a * q1, dim=-1)
                root_states[:, 7:10] = motion_base_lin_vel
                root_states[:, 10:] = motion_base_ang_vel
                robot.write_root_state_to_sim(root_states)
                joint_pos = robot.data.default_joint_pos.clone()
                joint_vel = robot.data.default_joint_vel.clone()
                joint_pos[:, robot_joint_indexes] = (1 - a) * prev[2] + a * cur[2]
                joint_vel[:, robot_joint_indexes] = motion_dof_vel
                if args_cli.robot_drive == "teleport" or prev is cur:
                    robot.write_joint_state_to_sim(joint_pos, joint_vel)
                robot.set_joint_position_target(joint_pos)
                robot.set_joint_velocity_target(joint_vel)
                robot.write_data_to_sim()
                sim.step(render=False)
                scene.update(sim.get_physics_dt())
            prev = cur

        # set root state
        root_states = robot.data.default_root_state.clone()
        root_states[:, :3] = motion_base_pos
        root_states[:, :2] += scene.env_origins[:, :2]
        root_states[:, 3:7] = motion_base_rot
        root_states[:, 7:10] = motion_base_lin_vel
        root_states[:, 10:] = motion_base_ang_vel
        # write_root_state_to_sim reads [:7] as the link-frame pose and [7:] as the
        # center-of-mass velocity, which is the source file's convention exactly.
        robot.write_root_state_to_sim(root_states)

        # set joint state
        joint_pos = robot.data.default_joint_pos.clone()
        joint_vel = robot.data.default_joint_vel.clone()
        joint_pos[:, robot_joint_indexes] = motion_dof_pos
        joint_vel[:, robot_joint_indexes] = motion_dof_vel
        # With --robot_drive pd the joints are left where the actuators put them (after frame 0).
        if not (args_cli.object_physics and args_cli.robot_drive == "pd" and log["joint_pos"]):
            robot.write_joint_state_to_sim(joint_pos, joint_vel)

        # set object state (kinematic replay, same convention as the robot root above)
        if not args_cli.object_physics:
            object_states = obj.data.default_root_state.clone()
            object_states[:, :3] = motion_object_pos
            object_states[:, :2] += scene.env_origins[:, :2]
            object_states[:, 3:7] = motion_object_rot
            object_states[:, 7:10] = motion_object_lin_vel
            object_states[:, 10:] = motion_object_ang_vel
            obj.write_root_state_to_sim(object_states)

        # Move the offscreen camera with the robot before rendering this frame.
        # The camera itself is a real Isaac Lab Camera sensor; this works in
        # --headless mode because --video forces enable_cameras=True above.
        if camera is not None:
            # Follow the root horizontally only. Tying the look-at height to the root as well makes the frame
            # dive whenever the robot squats -- which is most of a pick-up motion -- and crops the feet.
            # The height is pinned to the standing root height of the first frame instead.
            if camera_anchor_z is None:
                camera_anchor_z = root_states[0, 2].item()
                if args_cli.camera_view == "front":
                    # Rotate the offset by the frame-0 heading only, so the camera does not swing as the robot turns.
                    w, x, y, z = root_states[0, 3:7].tolist()
                    yaw = np.arctan2(2 * (w * z + x * y), 1 - 2 * (y * y + z * z))
                    ox, oy, oz = (2.2, 0.0, 0.6) if tuple(args_cli.camera_offset) == (1.8, 1.8, 0.6) else args_cli.camera_offset
                    camera_offset = torch.tensor(
                        [[ox * np.cos(yaw) - oy * np.sin(yaw), ox * np.sin(yaw) + oy * np.cos(yaw), oz]],
                        device=sim.device, dtype=torch.float32,
                    )  # fmt: skip
            target = root_states[:, :3] + camera_lookat_offset
            target[:, 2] = camera_anchor_z + camera_lookat_offset[0, 2]
            eye = target + camera_offset
            camera.set_world_poses_from_view(eye, target)

        # Kinematic replay only: render the state we just wrote; do not advance physics.
        sim.render()
        scene.update(sim.get_physics_dt())

        if camera is not None and video_writer is not None:
            video_writer.append(camera.data.output["rgb"][0])

        # Keep the interactive viewport useful as well.
        if sim.has_gui():
            pos_lookat = root_states[0, :3].cpu().numpy()
            sim.set_camera_view(
                pos_lookat + np.asarray(args_cli.camera_offset),
                pos_lookat + np.asarray(args_cli.camera_lookat_offset),
            )

        if not file_saved:
            log["joint_pos"].append(robot.data.joint_pos[0, :].cpu().numpy().copy())
            log["joint_vel"].append(robot.data.joint_vel[0, :].cpu().numpy().copy())
            log["body_pos_w"].append(robot.data.body_pos_w[0, :].cpu().numpy().copy())
            log["body_quat_w"].append(robot.data.body_quat_w[0, :].cpu().numpy().copy())
            log["body_lin_vel_w"].append(robot.data.body_lin_vel_w[0, :].cpu().numpy().copy())
            log["body_ang_vel_w"].append(robot.data.body_ang_vel_w[0, :].cpu().numpy().copy())
            if args_cli.object_physics:
                log["object_pos_w"].append((obj.data.root_pos_w[0] - scene.env_origins[0]).cpu().numpy().copy())
                log["object_quat_w"].append(obj.data.root_quat_w[0].cpu().numpy().copy())
                log["object_lin_vel_w"].append(obj.data.root_lin_vel_w[0].cpu().numpy().copy())
                log["object_ang_vel_w"].append(obj.data.root_ang_vel_w[0].cpu().numpy().copy())
                log.setdefault("ref_object_pos_w", []).append(motion_object_pos[0].cpu().numpy().copy())
            else:
                log["object_pos_w"].append(motion_object_pos[0, :].cpu().numpy().copy())
                log["object_quat_w"].append(motion_object_rot[0, :].cpu().numpy().copy())
                log["object_lin_vel_w"].append(motion_object_lin_vel[0, :].cpu().numpy().copy())
                log["object_ang_vel_w"].append(motion_object_ang_vel[0, :].cpu().numpy().copy())
            log["contact"].append(motion_contact[0, :].cpu().numpy().copy())

        if reset_flag and not file_saved:
            file_saved = True
            for k in (
                "joint_pos",
                "joint_vel",
                "body_pos_w",
                "body_quat_w",
                "body_lin_vel_w",
                "body_ang_vel_w",
                "object_pos_w",
                "object_quat_w",
                "object_lin_vel_w",
                "object_ang_vel_w",
                "contact",
            ):
                log[k] = np.stack(log[k], axis=0)

            report_bake_quality(log, motion, robot)
            if args_cli.object_physics:
                ref_obj = np.stack(log.pop("ref_object_pos_w"))
                sim_obj = log["object_pos_w"]
                err = np.linalg.norm(sim_obj - ref_obj, axis=-1)
                z0 = ref_obj[0, 2]
                lifted = ref_obj[:, 2] > z0 + 0.10
                print(f"[PHYSICS]: object max lift  sim {sim_obj[:, 2].max() - z0:+.3f} m   ref {ref_obj[:, 2].max() - z0:+.3f} m")
                print(f"[PHYSICS]: object error     mean {err.mean():.3f} m   max {err.max():.3f} m   final {err[-1]:.3f} m")
                if lifted.any():
                    print(f"[PHYSICS]: carried (within 10 cm while ref lifted): {(err[lifted] < 0.10).mean() * 100:.0f}%")
            np.savez(f"{args_cli.output_name}", **log)
            print(f"[INFO]: Motion saved to {args_cli.output_name}")
            if video_writer is not None:
                video_writer.close()
            return


def setup_object_physics(obj: RigidObject, scene: InteractiveScene, motion: "InterMimicMotionLoader"):
    """Mass, collider offsets, frame-0 pose and table slab for a physically simulated object."""
    import trimesh

    view = obj.root_physx_view
    ids = torch.arange(view.count, device="cpu")
    mass0 = view.get_masses().clone()
    view.set_masses(torch.full_like(mass0, args_cli.object_mass), ids)
    view.set_inertias(view.get_inertias() * (args_cli.object_mass / mass0.view(-1, 1)), ids)
    view.set_contact_offsets(torch.full_like(view.get_contact_offsets(), 0.02), ids)
    view.set_rest_offsets(torch.full_like(view.get_rest_offsets(), 0.001), ids)

    pos0, quat0 = motion.motion_object_poss[0], motion.motion_object_rots[0]
    state = obj.data.default_root_state.clone()
    state[:, :3] = pos0
    state[:, :2] += scene.env_origins[:, :2]
    state[:, 3:7] = quat0
    state[:, 7:] = 0.0
    obj.write_root_state_to_sim(state)

    w, x, y, z = quat0.cpu().numpy()
    rot = np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])  # fmt: skip
    vertices = np.asarray(trimesh.load(OBJECT_MESH, force="mesh").vertices)
    bottom = float((vertices @ rot.T)[:, 2].min() + pos0[2].item())
    support = scene["support"]
    slab = support.data.default_root_state.clone()
    slab[:, 3:7] = torch.tensor([1.0, 0.0, 0.0, 0.0], device=slab.device)
    if bottom > SUPPORT_MIN_HEIGHT:
        slab[:, :3] = torch.tensor([pos0[0].item(), pos0[1].item(), bottom - 0.5 * SUPPORT_SIZE[2]], device=slab.device)
        slab[:, :2] += scene.env_origins[:, :2]
    else:
        slab[:, :3] = torch.tensor([0.0, 0.0, -10.0], device=slab.device)
    support.write_root_state_to_sim(slab)
    print(
        f"[PHYSICS]: object {args_cli.object_mass} kg, bottom {bottom:+.3f} m ->"
        f" {'table slab' if bottom > SUPPORT_MIN_HEIGHT else 'floor'}; robot kinematic, object simulated",
        flush=True,
    )


def report_bake_quality(log: dict, motion: InterMimicMotionLoader, robot):
    """Cross-checks the regenerated bodies against the source file."""
    root_body_index = 0
    src_root_pos = motion.motion_base_poss.cpu().numpy()
    baked_root_pos = log["body_pos_w"][:, root_body_index]
    pos_err = np.abs(baked_root_pos - src_root_pos).max()

    src_root_vel = motion.source_body_lin_vels[:, root_body_index].cpu().numpy()
    baked_root_vel = log["body_lin_vel_w"][:, root_body_index]
    vel_err = np.abs(baked_root_vel - src_root_vel).max()

    min_z = log["body_pos_w"][..., 2].min()
    min_z_body = robot.body_names[int(np.argmin(log["body_pos_w"][..., 2].min(axis=0)))]

    obj_min_z = log["object_pos_w"][..., 2].min()
    obj_max_z = log["object_pos_w"][..., 2].max()

    print("[CHECK]: ---- bake quality ----")
    print(f"[CHECK]: frames baked                    : {log['body_pos_w'].shape[0]}")
    print(f"[CHECK]: root pos round-trip (max abs)   : {pos_err:.6f} m   (expect ~0)")
    print(f"[CHECK]: root lin vel round-trip (max abs): {vel_err:.6f} m/s (expect ~0)")
    print(f"[CHECK]: lowest body over the motion     : {min_z:.4f} m on '{min_z_body}'")
    print(f"[CHECK]: object height range              : [{obj_min_z:.4f}, {obj_max_z:.4f}] m")
    if pos_err > 1e-3:
        print("[CHECK]: WARNING root position did not round-trip; the source root frame likely differs from Trunk.")
    if vel_err > 1e-2:
        print("[CHECK]: WARNING root velocity did not round-trip; check the source velocity reference point.")
    if min_z < -0.02:
        print("[CHECK]: WARNING bodies penetrate the ground plane; the motion may need a z offset.")
    if obj_min_z < -0.02:
        print("[CHECK]: WARNING object penetrates the ground plane; check the object frame convention.")


def main():
    """Main function."""
    # Load kit helper
    sim_cfg = sim_utils.SimulationCfg(device=args_cli.device)
    sim_cfg.dt = 1.0 / args_cli.output_fps
    if args_cli.object_physics:
        sim_cfg.dt /= args_cli.substeps  # 0.005 s at 50 fps, as in training
    sim = SimulationContext(sim_cfg)
    # Design scene
    scene_cfg = ReplayMotionsSceneCfg(num_envs=1, env_spacing=2.0)
    if args_cli.object_physics:
        scene_cfg.support = RigidObjectCfg(
            prim_path="{ENV_REGEX_NS}/Support",
            spawn=sim_utils.CuboidCfg(
                size=SUPPORT_SIZE,
                rigid_props=sim_utils.RigidBodyPropertiesCfg(kinematic_enabled=True),
                collision_props=sim_utils.CollisionPropertiesCfg(),
                visual_material=sim_utils.PreviewSurfaceCfg(diffuse_color=(0.35, 0.3, 0.25)),
            ),
            init_state=RigidObjectCfg.InitialStateCfg(pos=(0.0, 0.0, -10.0)),
        )
    if args_cli.video is not None:
        scene_cfg.camera = CameraCfg(
            prim_path="{ENV_REGEX_NS}/RenderCamera",
            update_period=0.0,
            height=args_cli.video_height,
            width=args_cli.video_width,
            data_types=["rgb"],
            spawn=sim_utils.PinholeCameraCfg(
                focal_length=args_cli.camera_focal,
                focus_distance=400.0,
                horizontal_aperture=20.955,
                clipping_range=(0.1, 1.0e5),
            ),
        )
    scene = InteractiveScene(scene_cfg)
    if args_cli.object_physics and not args_cli.support_collides_robot:
        # Table only touches the object: filter every robot link against it (must be authored before sim.reset()).
        from pxr import Usd, UsdPhysics

        stage = sim.stage
        for env_ns in scene.env_prim_paths:
            rel = UsdPhysics.FilteredPairsAPI.Apply(stage.GetPrimAtPath(f"{env_ns}/Support")).CreateFilteredPairsRel()
            links = [
                prim.GetPath()
                for prim in Usd.PrimRange(stage.GetPrimAtPath(f"{env_ns}/Robot"))
                if prim.HasAPI(UsdPhysics.RigidBodyAPI)
            ]
            for link in links:
                rel.AddTarget(link)
        print(f"[PHYSICS]: table collision filtered against {len(links)} robot links", flush=True)
    # Play the simulator
    sim.reset()
    # Now we are ready!
    print("[INFO]: Setup complete...")
    # Run the simulator
    run_simulator(sim, scene)


if __name__ == "__main__":
    # Run the one-shot bake/render job. All user outputs (NPZ + MP4) are fully
    # flushed before main() returns.
    main()

    # In headless camera workflows, Isaac Sim can hang during its default
    # graceful shutdown while waiting on Replicator/Kit cleanup. This script is
    # a one-shot renderer, so there is nothing left to preserve after main().
    # Skip those shutdown waits and terminate Kit immediately.
    print("[INFO]: Closing Isaac Sim...", flush=True)
    simulation_app.close(wait_for_replicator=False, skip_cleanup=True)
